// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.33.4
// source: axelar/reward/v1beta1/tx.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { Any } from "../../../google/protobuf/any";
import { messageTypeRegistry } from "../../../typeRegistry";
import { Params } from "./params";

export const protobufPackage = "axelar.reward.v1beta1";

export interface RefundMsgRequest {
  $type: "axelar.reward.v1beta1.RefundMsgRequest";
  /**
   * DEPRECATED: This field is deprecated but must remain to ensure backward
   * compatibility. Removing this field would break decoding of historical
   * transactions. DO NOT use in new code.
   *
   * @deprecated
   */
  senderDeprecated: Buffer;
  innerMessage?: Any | undefined;
  sender: string;
}

export interface RefundMsgResponse {
  $type: "axelar.reward.v1beta1.RefundMsgResponse";
  data: Buffer;
  log: string;
}

export interface UpdateParamsRequest {
  $type: "axelar.reward.v1beta1.UpdateParamsRequest";
  authority: string;
  params?: Params | undefined;
}

export interface UpdateParamsResponse {
  $type: "axelar.reward.v1beta1.UpdateParamsResponse";
}

function createBaseRefundMsgRequest(): RefundMsgRequest {
  return {
    $type: "axelar.reward.v1beta1.RefundMsgRequest",
    senderDeprecated: Buffer.alloc(0),
    innerMessage: undefined,
    sender: "",
  };
}

export const RefundMsgRequest = {
  $type: "axelar.reward.v1beta1.RefundMsgRequest" as const,

  encode(message: RefundMsgRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.senderDeprecated.length !== 0) {
      writer.uint32(10).bytes(message.senderDeprecated);
    }
    if (message.innerMessage !== undefined) {
      Any.encode(message.innerMessage, writer.uint32(18).fork()).ldelim();
    }
    if (message.sender !== "") {
      writer.uint32(26).string(message.sender);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RefundMsgRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRefundMsgRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.senderDeprecated = reader.bytes() as Buffer;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.innerMessage = Any.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.sender = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RefundMsgRequest {
    return {
      $type: RefundMsgRequest.$type,
      senderDeprecated: isSet(object.senderDeprecated)
        ? Buffer.from(bytesFromBase64(object.senderDeprecated))
        : Buffer.alloc(0),
      innerMessage: isSet(object.innerMessage) ? Any.fromJSON(object.innerMessage) : undefined,
      sender: isSet(object.sender) ? gt.String(object.sender) : "",
    };
  },

  toJSON(message: RefundMsgRequest): unknown {
    const obj: any = {};
    if (message.senderDeprecated.length !== 0) {
      obj.senderDeprecated = base64FromBytes(message.senderDeprecated);
    }
    if (message.innerMessage !== undefined) {
      obj.innerMessage = Any.toJSON(message.innerMessage);
    }
    if (message.sender !== "") {
      obj.sender = message.sender;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RefundMsgRequest>, I>>(base?: I): RefundMsgRequest {
    return RefundMsgRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RefundMsgRequest>, I>>(object: I): RefundMsgRequest {
    const message = createBaseRefundMsgRequest();
    message.senderDeprecated = object.senderDeprecated ?? Buffer.alloc(0);
    message.innerMessage =
      object.innerMessage !== undefined && object.innerMessage !== null
        ? Any.fromPartial(object.innerMessage)
        : undefined;
    message.sender = object.sender ?? "";
    return message;
  },
};

messageTypeRegistry.set(RefundMsgRequest.$type, RefundMsgRequest);

function createBaseRefundMsgResponse(): RefundMsgResponse {
  return { $type: "axelar.reward.v1beta1.RefundMsgResponse", data: Buffer.alloc(0), log: "" };
}

export const RefundMsgResponse = {
  $type: "axelar.reward.v1beta1.RefundMsgResponse" as const,

  encode(message: RefundMsgResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.data.length !== 0) {
      writer.uint32(10).bytes(message.data);
    }
    if (message.log !== "") {
      writer.uint32(18).string(message.log);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RefundMsgResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRefundMsgResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.data = reader.bytes() as Buffer;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.log = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RefundMsgResponse {
    return {
      $type: RefundMsgResponse.$type,
      data: isSet(object.data) ? Buffer.from(bytesFromBase64(object.data)) : Buffer.alloc(0),
      log: isSet(object.log) ? gt.String(object.log) : "",
    };
  },

  toJSON(message: RefundMsgResponse): unknown {
    const obj: any = {};
    if (message.data.length !== 0) {
      obj.data = base64FromBytes(message.data);
    }
    if (message.log !== "") {
      obj.log = message.log;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RefundMsgResponse>, I>>(base?: I): RefundMsgResponse {
    return RefundMsgResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RefundMsgResponse>, I>>(object: I): RefundMsgResponse {
    const message = createBaseRefundMsgResponse();
    message.data = object.data ?? Buffer.alloc(0);
    message.log = object.log ?? "";
    return message;
  },
};

messageTypeRegistry.set(RefundMsgResponse.$type, RefundMsgResponse);

function createBaseUpdateParamsRequest(): UpdateParamsRequest {
  return { $type: "axelar.reward.v1beta1.UpdateParamsRequest", authority: "", params: undefined };
}

export const UpdateParamsRequest = {
  $type: "axelar.reward.v1beta1.UpdateParamsRequest" as const,

  encode(message: UpdateParamsRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): UpdateParamsRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateParamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateParamsRequest {
    return {
      $type: UpdateParamsRequest.$type,
      authority: isSet(object.authority) ? gt.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: UpdateParamsRequest): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateParamsRequest>, I>>(base?: I): UpdateParamsRequest {
    return UpdateParamsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateParamsRequest>, I>>(object: I): UpdateParamsRequest {
    const message = createBaseUpdateParamsRequest();
    message.authority = object.authority ?? "";
    message.params =
      object.params !== undefined && object.params !== null ? Params.fromPartial(object.params) : undefined;
    return message;
  },
};

messageTypeRegistry.set(UpdateParamsRequest.$type, UpdateParamsRequest);

function createBaseUpdateParamsResponse(): UpdateParamsResponse {
  return { $type: "axelar.reward.v1beta1.UpdateParamsResponse" };
}

export const UpdateParamsResponse = {
  $type: "axelar.reward.v1beta1.UpdateParamsResponse" as const,

  encode(_: UpdateParamsResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): UpdateParamsResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): UpdateParamsResponse {
    return { $type: UpdateParamsResponse.$type };
  },

  toJSON(_: UpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateParamsResponse>, I>>(base?: I): UpdateParamsResponse {
    return UpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateParamsResponse>, I>>(_: I): UpdateParamsResponse {
    const message = createBaseUpdateParamsResponse();
    return message;
  },
};

messageTypeRegistry.set(UpdateParamsResponse.$type, UpdateParamsResponse);

declare const self: any | undefined;
declare const window: any | undefined;
declare const global: any | undefined;
const gt: any = (() => {
  if (typeof globalThis !== "undefined") {
    return globalThis;
  }
  if (typeof self !== "undefined") {
    return self;
  }
  if (typeof window !== "undefined") {
    return window;
  }
  if (typeof global !== "undefined") {
    return global;
  }
  throw "Unable to locate global object";
})();

function bytesFromBase64(b64: string): Uint8Array {
  return Uint8Array.from(gt.Buffer.from(b64, "base64"));
}

function base64FromBytes(arr: Uint8Array): string {
  return gt.Buffer.from(arr).toString("base64");
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends Long
  ? string | number | Long
  : T extends globalThis.Array<infer U>
  ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U>
  ? ReadonlyArray<DeepPartial<U>>
  : T extends {}
  ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P> | "$type">]: never };

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
