// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.21.12
// source: axelar/multisig/v1beta1/events.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { messageTypeRegistry } from "../../../typeRegistry";

export const protobufPackage = "axelar.multisig.v1beta1";

export interface KeygenStarted {
  $type: "axelar.multisig.v1beta1.KeygenStarted";
  module: string;
  keyId: string;
  participants: Buffer[];
}

export interface KeygenCompleted {
  $type: "axelar.multisig.v1beta1.KeygenCompleted";
  module: string;
  keyId: string;
}

export interface KeygenExpired {
  $type: "axelar.multisig.v1beta1.KeygenExpired";
  module: string;
  keyId: string;
}

export interface PubKeySubmitted {
  $type: "axelar.multisig.v1beta1.PubKeySubmitted";
  module: string;
  keyId: string;
  participant: Buffer;
  pubKey: Buffer;
}

export interface SigningStarted {
  $type: "axelar.multisig.v1beta1.SigningStarted";
  module: string;
  sigId: Long;
  keyId: string;
  pubKeys: { [key: string]: Buffer };
  payloadHash: Buffer;
  requestingModule: string;
}

export interface SigningStarted_PubKeysEntry {
  $type: "axelar.multisig.v1beta1.SigningStarted.PubKeysEntry";
  key: string;
  value: Buffer;
}

export interface SigningCompleted {
  $type: "axelar.multisig.v1beta1.SigningCompleted";
  module: string;
  sigId: Long;
}

export interface SigningExpired {
  $type: "axelar.multisig.v1beta1.SigningExpired";
  module: string;
  sigId: Long;
}

export interface SignatureSubmitted {
  $type: "axelar.multisig.v1beta1.SignatureSubmitted";
  module: string;
  sigId: Long;
  participant: Buffer;
  signature: Buffer;
}

export interface KeyAssigned {
  $type: "axelar.multisig.v1beta1.KeyAssigned";
  module: string;
  chain: string;
  keyId: string;
}

export interface KeyRotated {
  $type: "axelar.multisig.v1beta1.KeyRotated";
  module: string;
  chain: string;
  keyId: string;
}

export interface KeygenOptOut {
  $type: "axelar.multisig.v1beta1.KeygenOptOut";
  participant: Buffer;
}

export interface KeygenOptIn {
  $type: "axelar.multisig.v1beta1.KeygenOptIn";
  participant: Buffer;
}

function createBaseKeygenStarted(): KeygenStarted {
  return { $type: "axelar.multisig.v1beta1.KeygenStarted", module: "", keyId: "", participants: [] };
}

export const KeygenStarted = {
  $type: "axelar.multisig.v1beta1.KeygenStarted" as const,

  encode(message: KeygenStarted, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.module !== "") {
      writer.uint32(10).string(message.module);
    }
    if (message.keyId !== "") {
      writer.uint32(18).string(message.keyId);
    }
    for (const v of message.participants) {
      writer.uint32(26).bytes(v!);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): KeygenStarted {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeygenStarted();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.module = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.keyId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.participants.push(reader.bytes() as Buffer);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): KeygenStarted {
    return {
      $type: KeygenStarted.$type,
      module: isSet(object.module) ? gt.String(object.module) : "",
      keyId: isSet(object.keyId) ? gt.String(object.keyId) : "",
      participants: gt.Array.isArray(object?.participants)
        ? object.participants.map((e: any) => Buffer.from(bytesFromBase64(e)))
        : [],
    };
  },

  toJSON(message: KeygenStarted): unknown {
    const obj: any = {};
    if (message.module !== "") {
      obj.module = message.module;
    }
    if (message.keyId !== "") {
      obj.keyId = message.keyId;
    }
    if (message.participants?.length) {
      obj.participants = message.participants.map((e) => base64FromBytes(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<KeygenStarted>, I>>(base?: I): KeygenStarted {
    return KeygenStarted.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KeygenStarted>, I>>(object: I): KeygenStarted {
    const message = createBaseKeygenStarted();
    message.module = object.module ?? "";
    message.keyId = object.keyId ?? "";
    message.participants = object.participants?.map((e) => e) || [];
    return message;
  },
};

messageTypeRegistry.set(KeygenStarted.$type, KeygenStarted);

function createBaseKeygenCompleted(): KeygenCompleted {
  return { $type: "axelar.multisig.v1beta1.KeygenCompleted", module: "", keyId: "" };
}

export const KeygenCompleted = {
  $type: "axelar.multisig.v1beta1.KeygenCompleted" as const,

  encode(message: KeygenCompleted, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.module !== "") {
      writer.uint32(10).string(message.module);
    }
    if (message.keyId !== "") {
      writer.uint32(18).string(message.keyId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): KeygenCompleted {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeygenCompleted();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.module = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.keyId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): KeygenCompleted {
    return {
      $type: KeygenCompleted.$type,
      module: isSet(object.module) ? gt.String(object.module) : "",
      keyId: isSet(object.keyId) ? gt.String(object.keyId) : "",
    };
  },

  toJSON(message: KeygenCompleted): unknown {
    const obj: any = {};
    if (message.module !== "") {
      obj.module = message.module;
    }
    if (message.keyId !== "") {
      obj.keyId = message.keyId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<KeygenCompleted>, I>>(base?: I): KeygenCompleted {
    return KeygenCompleted.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KeygenCompleted>, I>>(object: I): KeygenCompleted {
    const message = createBaseKeygenCompleted();
    message.module = object.module ?? "";
    message.keyId = object.keyId ?? "";
    return message;
  },
};

messageTypeRegistry.set(KeygenCompleted.$type, KeygenCompleted);

function createBaseKeygenExpired(): KeygenExpired {
  return { $type: "axelar.multisig.v1beta1.KeygenExpired", module: "", keyId: "" };
}

export const KeygenExpired = {
  $type: "axelar.multisig.v1beta1.KeygenExpired" as const,

  encode(message: KeygenExpired, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.module !== "") {
      writer.uint32(10).string(message.module);
    }
    if (message.keyId !== "") {
      writer.uint32(18).string(message.keyId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): KeygenExpired {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeygenExpired();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.module = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.keyId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): KeygenExpired {
    return {
      $type: KeygenExpired.$type,
      module: isSet(object.module) ? gt.String(object.module) : "",
      keyId: isSet(object.keyId) ? gt.String(object.keyId) : "",
    };
  },

  toJSON(message: KeygenExpired): unknown {
    const obj: any = {};
    if (message.module !== "") {
      obj.module = message.module;
    }
    if (message.keyId !== "") {
      obj.keyId = message.keyId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<KeygenExpired>, I>>(base?: I): KeygenExpired {
    return KeygenExpired.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KeygenExpired>, I>>(object: I): KeygenExpired {
    const message = createBaseKeygenExpired();
    message.module = object.module ?? "";
    message.keyId = object.keyId ?? "";
    return message;
  },
};

messageTypeRegistry.set(KeygenExpired.$type, KeygenExpired);

function createBasePubKeySubmitted(): PubKeySubmitted {
  return {
    $type: "axelar.multisig.v1beta1.PubKeySubmitted",
    module: "",
    keyId: "",
    participant: Buffer.alloc(0),
    pubKey: Buffer.alloc(0),
  };
}

export const PubKeySubmitted = {
  $type: "axelar.multisig.v1beta1.PubKeySubmitted" as const,

  encode(message: PubKeySubmitted, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.module !== "") {
      writer.uint32(10).string(message.module);
    }
    if (message.keyId !== "") {
      writer.uint32(18).string(message.keyId);
    }
    if (message.participant.length !== 0) {
      writer.uint32(26).bytes(message.participant);
    }
    if (message.pubKey.length !== 0) {
      writer.uint32(34).bytes(message.pubKey);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): PubKeySubmitted {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePubKeySubmitted();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.module = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.keyId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.participant = reader.bytes() as Buffer;
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.pubKey = reader.bytes() as Buffer;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PubKeySubmitted {
    return {
      $type: PubKeySubmitted.$type,
      module: isSet(object.module) ? gt.String(object.module) : "",
      keyId: isSet(object.keyId) ? gt.String(object.keyId) : "",
      participant: isSet(object.participant)
        ? Buffer.from(bytesFromBase64(object.participant))
        : Buffer.alloc(0),
      pubKey: isSet(object.pubKey) ? Buffer.from(bytesFromBase64(object.pubKey)) : Buffer.alloc(0),
    };
  },

  toJSON(message: PubKeySubmitted): unknown {
    const obj: any = {};
    if (message.module !== "") {
      obj.module = message.module;
    }
    if (message.keyId !== "") {
      obj.keyId = message.keyId;
    }
    if (message.participant.length !== 0) {
      obj.participant = base64FromBytes(message.participant);
    }
    if (message.pubKey.length !== 0) {
      obj.pubKey = base64FromBytes(message.pubKey);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PubKeySubmitted>, I>>(base?: I): PubKeySubmitted {
    return PubKeySubmitted.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PubKeySubmitted>, I>>(object: I): PubKeySubmitted {
    const message = createBasePubKeySubmitted();
    message.module = object.module ?? "";
    message.keyId = object.keyId ?? "";
    message.participant = object.participant ?? Buffer.alloc(0);
    message.pubKey = object.pubKey ?? Buffer.alloc(0);
    return message;
  },
};

messageTypeRegistry.set(PubKeySubmitted.$type, PubKeySubmitted);

function createBaseSigningStarted(): SigningStarted {
  return {
    $type: "axelar.multisig.v1beta1.SigningStarted",
    module: "",
    sigId: Long.UZERO,
    keyId: "",
    pubKeys: {},
    payloadHash: Buffer.alloc(0),
    requestingModule: "",
  };
}

export const SigningStarted = {
  $type: "axelar.multisig.v1beta1.SigningStarted" as const,

  encode(message: SigningStarted, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.module !== "") {
      writer.uint32(10).string(message.module);
    }
    if (!message.sigId.equals(Long.UZERO)) {
      writer.uint32(16).uint64(message.sigId);
    }
    if (message.keyId !== "") {
      writer.uint32(26).string(message.keyId);
    }
    Object.entries(message.pubKeys).forEach(([key, value]) => {
      SigningStarted_PubKeysEntry.encode(
        {
          $type: "axelar.multisig.v1beta1.SigningStarted.PubKeysEntry",
          key: key as any,
          value,
        },
        writer.uint32(34).fork(),
      ).ldelim();
    });
    if (message.payloadHash.length !== 0) {
      writer.uint32(42).bytes(message.payloadHash);
    }
    if (message.requestingModule !== "") {
      writer.uint32(50).string(message.requestingModule);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SigningStarted {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSigningStarted();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.module = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.sigId = reader.uint64() as Long;
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.keyId = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          const entry4 = SigningStarted_PubKeysEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.pubKeys[entry4.key] = entry4.value;
          }
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.payloadHash = reader.bytes() as Buffer;
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.requestingModule = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SigningStarted {
    return {
      $type: SigningStarted.$type,
      module: isSet(object.module) ? gt.String(object.module) : "",
      sigId: isSet(object.sigId) ? Long.fromValue(object.sigId) : Long.UZERO,
      keyId: isSet(object.keyId) ? gt.String(object.keyId) : "",
      pubKeys: isObject(object.pubKeys)
        ? Object.entries(object.pubKeys).reduce<{ [key: string]: Buffer }>((acc, [key, value]) => {
            acc[key] = Buffer.from(bytesFromBase64(value as string));
            return acc;
          }, {})
        : {},
      payloadHash: isSet(object.payloadHash)
        ? Buffer.from(bytesFromBase64(object.payloadHash))
        : Buffer.alloc(0),
      requestingModule: isSet(object.requestingModule) ? gt.String(object.requestingModule) : "",
    };
  },

  toJSON(message: SigningStarted): unknown {
    const obj: any = {};
    if (message.module !== "") {
      obj.module = message.module;
    }
    if (!message.sigId.equals(Long.UZERO)) {
      obj.sigId = (message.sigId || Long.UZERO).toString();
    }
    if (message.keyId !== "") {
      obj.keyId = message.keyId;
    }
    if (message.pubKeys) {
      const entries = Object.entries(message.pubKeys);
      if (entries.length > 0) {
        obj.pubKeys = {};
        entries.forEach(([k, v]) => {
          obj.pubKeys[k] = base64FromBytes(v);
        });
      }
    }
    if (message.payloadHash.length !== 0) {
      obj.payloadHash = base64FromBytes(message.payloadHash);
    }
    if (message.requestingModule !== "") {
      obj.requestingModule = message.requestingModule;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SigningStarted>, I>>(base?: I): SigningStarted {
    return SigningStarted.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SigningStarted>, I>>(object: I): SigningStarted {
    const message = createBaseSigningStarted();
    message.module = object.module ?? "";
    message.sigId =
      object.sigId !== undefined && object.sigId !== null ? Long.fromValue(object.sigId) : Long.UZERO;
    message.keyId = object.keyId ?? "";
    message.pubKeys = Object.entries(object.pubKeys ?? {}).reduce<{ [key: string]: Buffer }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[key] = value;
        }
        return acc;
      },
      {},
    );
    message.payloadHash = object.payloadHash ?? Buffer.alloc(0);
    message.requestingModule = object.requestingModule ?? "";
    return message;
  },
};

messageTypeRegistry.set(SigningStarted.$type, SigningStarted);

function createBaseSigningStarted_PubKeysEntry(): SigningStarted_PubKeysEntry {
  return { $type: "axelar.multisig.v1beta1.SigningStarted.PubKeysEntry", key: "", value: Buffer.alloc(0) };
}

export const SigningStarted_PubKeysEntry = {
  $type: "axelar.multisig.v1beta1.SigningStarted.PubKeysEntry" as const,

  encode(message: SigningStarted_PubKeysEntry, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value.length !== 0) {
      writer.uint32(18).bytes(message.value);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SigningStarted_PubKeysEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSigningStarted_PubKeysEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.value = reader.bytes() as Buffer;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SigningStarted_PubKeysEntry {
    return {
      $type: SigningStarted_PubKeysEntry.$type,
      key: isSet(object.key) ? gt.String(object.key) : "",
      value: isSet(object.value) ? Buffer.from(bytesFromBase64(object.value)) : Buffer.alloc(0),
    };
  },

  toJSON(message: SigningStarted_PubKeysEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value.length !== 0) {
      obj.value = base64FromBytes(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SigningStarted_PubKeysEntry>, I>>(
    base?: I,
  ): SigningStarted_PubKeysEntry {
    return SigningStarted_PubKeysEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SigningStarted_PubKeysEntry>, I>>(
    object: I,
  ): SigningStarted_PubKeysEntry {
    const message = createBaseSigningStarted_PubKeysEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? Buffer.alloc(0);
    return message;
  },
};

messageTypeRegistry.set(SigningStarted_PubKeysEntry.$type, SigningStarted_PubKeysEntry);

function createBaseSigningCompleted(): SigningCompleted {
  return { $type: "axelar.multisig.v1beta1.SigningCompleted", module: "", sigId: Long.UZERO };
}

export const SigningCompleted = {
  $type: "axelar.multisig.v1beta1.SigningCompleted" as const,

  encode(message: SigningCompleted, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.module !== "") {
      writer.uint32(10).string(message.module);
    }
    if (!message.sigId.equals(Long.UZERO)) {
      writer.uint32(16).uint64(message.sigId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SigningCompleted {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSigningCompleted();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.module = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.sigId = reader.uint64() as Long;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SigningCompleted {
    return {
      $type: SigningCompleted.$type,
      module: isSet(object.module) ? gt.String(object.module) : "",
      sigId: isSet(object.sigId) ? Long.fromValue(object.sigId) : Long.UZERO,
    };
  },

  toJSON(message: SigningCompleted): unknown {
    const obj: any = {};
    if (message.module !== "") {
      obj.module = message.module;
    }
    if (!message.sigId.equals(Long.UZERO)) {
      obj.sigId = (message.sigId || Long.UZERO).toString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SigningCompleted>, I>>(base?: I): SigningCompleted {
    return SigningCompleted.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SigningCompleted>, I>>(object: I): SigningCompleted {
    const message = createBaseSigningCompleted();
    message.module = object.module ?? "";
    message.sigId =
      object.sigId !== undefined && object.sigId !== null ? Long.fromValue(object.sigId) : Long.UZERO;
    return message;
  },
};

messageTypeRegistry.set(SigningCompleted.$type, SigningCompleted);

function createBaseSigningExpired(): SigningExpired {
  return { $type: "axelar.multisig.v1beta1.SigningExpired", module: "", sigId: Long.UZERO };
}

export const SigningExpired = {
  $type: "axelar.multisig.v1beta1.SigningExpired" as const,

  encode(message: SigningExpired, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.module !== "") {
      writer.uint32(10).string(message.module);
    }
    if (!message.sigId.equals(Long.UZERO)) {
      writer.uint32(16).uint64(message.sigId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SigningExpired {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSigningExpired();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.module = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.sigId = reader.uint64() as Long;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SigningExpired {
    return {
      $type: SigningExpired.$type,
      module: isSet(object.module) ? gt.String(object.module) : "",
      sigId: isSet(object.sigId) ? Long.fromValue(object.sigId) : Long.UZERO,
    };
  },

  toJSON(message: SigningExpired): unknown {
    const obj: any = {};
    if (message.module !== "") {
      obj.module = message.module;
    }
    if (!message.sigId.equals(Long.UZERO)) {
      obj.sigId = (message.sigId || Long.UZERO).toString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SigningExpired>, I>>(base?: I): SigningExpired {
    return SigningExpired.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SigningExpired>, I>>(object: I): SigningExpired {
    const message = createBaseSigningExpired();
    message.module = object.module ?? "";
    message.sigId =
      object.sigId !== undefined && object.sigId !== null ? Long.fromValue(object.sigId) : Long.UZERO;
    return message;
  },
};

messageTypeRegistry.set(SigningExpired.$type, SigningExpired);

function createBaseSignatureSubmitted(): SignatureSubmitted {
  return {
    $type: "axelar.multisig.v1beta1.SignatureSubmitted",
    module: "",
    sigId: Long.UZERO,
    participant: Buffer.alloc(0),
    signature: Buffer.alloc(0),
  };
}

export const SignatureSubmitted = {
  $type: "axelar.multisig.v1beta1.SignatureSubmitted" as const,

  encode(message: SignatureSubmitted, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.module !== "") {
      writer.uint32(10).string(message.module);
    }
    if (!message.sigId.equals(Long.UZERO)) {
      writer.uint32(16).uint64(message.sigId);
    }
    if (message.participant.length !== 0) {
      writer.uint32(26).bytes(message.participant);
    }
    if (message.signature.length !== 0) {
      writer.uint32(34).bytes(message.signature);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SignatureSubmitted {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignatureSubmitted();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.module = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.sigId = reader.uint64() as Long;
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.participant = reader.bytes() as Buffer;
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.signature = reader.bytes() as Buffer;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SignatureSubmitted {
    return {
      $type: SignatureSubmitted.$type,
      module: isSet(object.module) ? gt.String(object.module) : "",
      sigId: isSet(object.sigId) ? Long.fromValue(object.sigId) : Long.UZERO,
      participant: isSet(object.participant)
        ? Buffer.from(bytesFromBase64(object.participant))
        : Buffer.alloc(0),
      signature: isSet(object.signature) ? Buffer.from(bytesFromBase64(object.signature)) : Buffer.alloc(0),
    };
  },

  toJSON(message: SignatureSubmitted): unknown {
    const obj: any = {};
    if (message.module !== "") {
      obj.module = message.module;
    }
    if (!message.sigId.equals(Long.UZERO)) {
      obj.sigId = (message.sigId || Long.UZERO).toString();
    }
    if (message.participant.length !== 0) {
      obj.participant = base64FromBytes(message.participant);
    }
    if (message.signature.length !== 0) {
      obj.signature = base64FromBytes(message.signature);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SignatureSubmitted>, I>>(base?: I): SignatureSubmitted {
    return SignatureSubmitted.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SignatureSubmitted>, I>>(object: I): SignatureSubmitted {
    const message = createBaseSignatureSubmitted();
    message.module = object.module ?? "";
    message.sigId =
      object.sigId !== undefined && object.sigId !== null ? Long.fromValue(object.sigId) : Long.UZERO;
    message.participant = object.participant ?? Buffer.alloc(0);
    message.signature = object.signature ?? Buffer.alloc(0);
    return message;
  },
};

messageTypeRegistry.set(SignatureSubmitted.$type, SignatureSubmitted);

function createBaseKeyAssigned(): KeyAssigned {
  return { $type: "axelar.multisig.v1beta1.KeyAssigned", module: "", chain: "", keyId: "" };
}

export const KeyAssigned = {
  $type: "axelar.multisig.v1beta1.KeyAssigned" as const,

  encode(message: KeyAssigned, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.module !== "") {
      writer.uint32(10).string(message.module);
    }
    if (message.chain !== "") {
      writer.uint32(18).string(message.chain);
    }
    if (message.keyId !== "") {
      writer.uint32(26).string(message.keyId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): KeyAssigned {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeyAssigned();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.module = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.chain = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.keyId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): KeyAssigned {
    return {
      $type: KeyAssigned.$type,
      module: isSet(object.module) ? gt.String(object.module) : "",
      chain: isSet(object.chain) ? gt.String(object.chain) : "",
      keyId: isSet(object.keyId) ? gt.String(object.keyId) : "",
    };
  },

  toJSON(message: KeyAssigned): unknown {
    const obj: any = {};
    if (message.module !== "") {
      obj.module = message.module;
    }
    if (message.chain !== "") {
      obj.chain = message.chain;
    }
    if (message.keyId !== "") {
      obj.keyId = message.keyId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<KeyAssigned>, I>>(base?: I): KeyAssigned {
    return KeyAssigned.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KeyAssigned>, I>>(object: I): KeyAssigned {
    const message = createBaseKeyAssigned();
    message.module = object.module ?? "";
    message.chain = object.chain ?? "";
    message.keyId = object.keyId ?? "";
    return message;
  },
};

messageTypeRegistry.set(KeyAssigned.$type, KeyAssigned);

function createBaseKeyRotated(): KeyRotated {
  return { $type: "axelar.multisig.v1beta1.KeyRotated", module: "", chain: "", keyId: "" };
}

export const KeyRotated = {
  $type: "axelar.multisig.v1beta1.KeyRotated" as const,

  encode(message: KeyRotated, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.module !== "") {
      writer.uint32(10).string(message.module);
    }
    if (message.chain !== "") {
      writer.uint32(18).string(message.chain);
    }
    if (message.keyId !== "") {
      writer.uint32(26).string(message.keyId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): KeyRotated {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeyRotated();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.module = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.chain = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.keyId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): KeyRotated {
    return {
      $type: KeyRotated.$type,
      module: isSet(object.module) ? gt.String(object.module) : "",
      chain: isSet(object.chain) ? gt.String(object.chain) : "",
      keyId: isSet(object.keyId) ? gt.String(object.keyId) : "",
    };
  },

  toJSON(message: KeyRotated): unknown {
    const obj: any = {};
    if (message.module !== "") {
      obj.module = message.module;
    }
    if (message.chain !== "") {
      obj.chain = message.chain;
    }
    if (message.keyId !== "") {
      obj.keyId = message.keyId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<KeyRotated>, I>>(base?: I): KeyRotated {
    return KeyRotated.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KeyRotated>, I>>(object: I): KeyRotated {
    const message = createBaseKeyRotated();
    message.module = object.module ?? "";
    message.chain = object.chain ?? "";
    message.keyId = object.keyId ?? "";
    return message;
  },
};

messageTypeRegistry.set(KeyRotated.$type, KeyRotated);

function createBaseKeygenOptOut(): KeygenOptOut {
  return { $type: "axelar.multisig.v1beta1.KeygenOptOut", participant: Buffer.alloc(0) };
}

export const KeygenOptOut = {
  $type: "axelar.multisig.v1beta1.KeygenOptOut" as const,

  encode(message: KeygenOptOut, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.participant.length !== 0) {
      writer.uint32(10).bytes(message.participant);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): KeygenOptOut {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeygenOptOut();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.participant = reader.bytes() as Buffer;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): KeygenOptOut {
    return {
      $type: KeygenOptOut.$type,
      participant: isSet(object.participant)
        ? Buffer.from(bytesFromBase64(object.participant))
        : Buffer.alloc(0),
    };
  },

  toJSON(message: KeygenOptOut): unknown {
    const obj: any = {};
    if (message.participant.length !== 0) {
      obj.participant = base64FromBytes(message.participant);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<KeygenOptOut>, I>>(base?: I): KeygenOptOut {
    return KeygenOptOut.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KeygenOptOut>, I>>(object: I): KeygenOptOut {
    const message = createBaseKeygenOptOut();
    message.participant = object.participant ?? Buffer.alloc(0);
    return message;
  },
};

messageTypeRegistry.set(KeygenOptOut.$type, KeygenOptOut);

function createBaseKeygenOptIn(): KeygenOptIn {
  return { $type: "axelar.multisig.v1beta1.KeygenOptIn", participant: Buffer.alloc(0) };
}

export const KeygenOptIn = {
  $type: "axelar.multisig.v1beta1.KeygenOptIn" as const,

  encode(message: KeygenOptIn, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.participant.length !== 0) {
      writer.uint32(10).bytes(message.participant);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): KeygenOptIn {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeygenOptIn();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.participant = reader.bytes() as Buffer;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): KeygenOptIn {
    return {
      $type: KeygenOptIn.$type,
      participant: isSet(object.participant)
        ? Buffer.from(bytesFromBase64(object.participant))
        : Buffer.alloc(0),
    };
  },

  toJSON(message: KeygenOptIn): unknown {
    const obj: any = {};
    if (message.participant.length !== 0) {
      obj.participant = base64FromBytes(message.participant);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<KeygenOptIn>, I>>(base?: I): KeygenOptIn {
    return KeygenOptIn.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KeygenOptIn>, I>>(object: I): KeygenOptIn {
    const message = createBaseKeygenOptIn();
    message.participant = object.participant ?? Buffer.alloc(0);
    return message;
  },
};

messageTypeRegistry.set(KeygenOptIn.$type, KeygenOptIn);

declare const self: any | undefined;
declare const window: any | undefined;
declare const global: any | undefined;
const gt: any = (() => {
  if (typeof globalThis !== "undefined") {
    return globalThis;
  }
  if (typeof self !== "undefined") {
    return self;
  }
  if (typeof window !== "undefined") {
    return window;
  }
  if (typeof global !== "undefined") {
    return global;
  }
  throw "Unable to locate global object";
})();

function bytesFromBase64(b64: string): Uint8Array {
  return Uint8Array.from(gt.Buffer.from(b64, "base64"));
}

function base64FromBytes(arr: Uint8Array): string {
  return gt.Buffer.from(arr).toString("base64");
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends Long
  ? string | number | Long
  : T extends globalThis.Array<infer U>
  ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U>
  ? ReadonlyArray<DeepPartial<U>>
  : T extends {}
  ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P> | "$type">]: never };

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
