"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.21.12
// source: axelar/snapshot/v1beta1/query.proto
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProxyByOperatorResponse = exports.ProxyByOperatorRequest = exports.OperatorByProxyResponse = exports.OperatorByProxyRequest = exports.ParamsResponse = exports.ParamsRequest = exports.QueryValidatorsResponse_Validator = exports.QueryValidatorsResponse_TssIllegibilityInfo = exports.QueryValidatorsResponse = exports.proxyByOperatorResponse_StatusToJSON = exports.proxyByOperatorResponse_StatusFromJSON = exports.ProxyByOperatorResponse_Status = exports.protobufPackage = void 0;
/* eslint-disable */
const long_1 = __importDefault(require("long"));
const minimal_1 = __importDefault(require("protobufjs/minimal"));
const typeRegistry_1 = require("../../../typeRegistry");
const params_1 = require("./params");
exports.protobufPackage = "axelar.snapshot.v1beta1";
var ProxyByOperatorResponse_Status;
(function (ProxyByOperatorResponse_Status) {
    ProxyByOperatorResponse_Status[ProxyByOperatorResponse_Status["STATUS_UNSPECIFIED"] = 0] = "STATUS_UNSPECIFIED";
    ProxyByOperatorResponse_Status[ProxyByOperatorResponse_Status["STATUS_ACTIVE"] = 1] = "STATUS_ACTIVE";
    ProxyByOperatorResponse_Status[ProxyByOperatorResponse_Status["STATUS_INACTIVE"] = 2] = "STATUS_INACTIVE";
    ProxyByOperatorResponse_Status[ProxyByOperatorResponse_Status["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(ProxyByOperatorResponse_Status = exports.ProxyByOperatorResponse_Status || (exports.ProxyByOperatorResponse_Status = {}));
function proxyByOperatorResponse_StatusFromJSON(object) {
    switch (object) {
        case 0:
        case "STATUS_UNSPECIFIED":
            return ProxyByOperatorResponse_Status.STATUS_UNSPECIFIED;
        case 1:
        case "STATUS_ACTIVE":
            return ProxyByOperatorResponse_Status.STATUS_ACTIVE;
        case 2:
        case "STATUS_INACTIVE":
            return ProxyByOperatorResponse_Status.STATUS_INACTIVE;
        case -1:
        case "UNRECOGNIZED":
        default:
            return ProxyByOperatorResponse_Status.UNRECOGNIZED;
    }
}
exports.proxyByOperatorResponse_StatusFromJSON = proxyByOperatorResponse_StatusFromJSON;
function proxyByOperatorResponse_StatusToJSON(object) {
    switch (object) {
        case ProxyByOperatorResponse_Status.STATUS_UNSPECIFIED:
            return "STATUS_UNSPECIFIED";
        case ProxyByOperatorResponse_Status.STATUS_ACTIVE:
            return "STATUS_ACTIVE";
        case ProxyByOperatorResponse_Status.STATUS_INACTIVE:
            return "STATUS_INACTIVE";
        case ProxyByOperatorResponse_Status.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
exports.proxyByOperatorResponse_StatusToJSON = proxyByOperatorResponse_StatusToJSON;
function createBaseQueryValidatorsResponse() {
    return { $type: "axelar.snapshot.v1beta1.QueryValidatorsResponse", validators: [] };
}
exports.QueryValidatorsResponse = {
    $type: "axelar.snapshot.v1beta1.QueryValidatorsResponse",
    encode(message, writer = minimal_1.default.Writer.create()) {
        for (const v of message.validators) {
            exports.QueryValidatorsResponse_Validator.encode(v, writer.uint32(10).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseQueryValidatorsResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.validators.push(exports.QueryValidatorsResponse_Validator.decode(reader, reader.uint32()));
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.QueryValidatorsResponse.$type,
            validators: gt.Array.isArray(object === null || object === void 0 ? void 0 : object.validators)
                ? object.validators.map((e) => exports.QueryValidatorsResponse_Validator.fromJSON(e))
                : [],
        };
    },
    toJSON(message) {
        var _a;
        const obj = {};
        if ((_a = message.validators) === null || _a === void 0 ? void 0 : _a.length) {
            obj.validators = message.validators.map((e) => exports.QueryValidatorsResponse_Validator.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return exports.QueryValidatorsResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a;
        const message = createBaseQueryValidatorsResponse();
        message.validators =
            ((_a = object.validators) === null || _a === void 0 ? void 0 : _a.map((e) => exports.QueryValidatorsResponse_Validator.fromPartial(e))) || [];
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.QueryValidatorsResponse.$type, exports.QueryValidatorsResponse);
function createBaseQueryValidatorsResponse_TssIllegibilityInfo() {
    return {
        $type: "axelar.snapshot.v1beta1.QueryValidatorsResponse.TssIllegibilityInfo",
        tombstoned: false,
        jailed: false,
        missedTooManyBlocks: false,
        noProxyRegistered: false,
        tssSuspended: false,
        proxyInsuficientFunds: false,
        staleTssHeartbeat: false,
    };
}
exports.QueryValidatorsResponse_TssIllegibilityInfo = {
    $type: "axelar.snapshot.v1beta1.QueryValidatorsResponse.TssIllegibilityInfo",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.tombstoned !== false) {
            writer.uint32(8).bool(message.tombstoned);
        }
        if (message.jailed !== false) {
            writer.uint32(16).bool(message.jailed);
        }
        if (message.missedTooManyBlocks !== false) {
            writer.uint32(24).bool(message.missedTooManyBlocks);
        }
        if (message.noProxyRegistered !== false) {
            writer.uint32(32).bool(message.noProxyRegistered);
        }
        if (message.tssSuspended !== false) {
            writer.uint32(40).bool(message.tssSuspended);
        }
        if (message.proxyInsuficientFunds !== false) {
            writer.uint32(48).bool(message.proxyInsuficientFunds);
        }
        if (message.staleTssHeartbeat !== false) {
            writer.uint32(56).bool(message.staleTssHeartbeat);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseQueryValidatorsResponse_TssIllegibilityInfo();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.tombstoned = reader.bool();
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.jailed = reader.bool();
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.missedTooManyBlocks = reader.bool();
                    continue;
                case 4:
                    if (tag !== 32) {
                        break;
                    }
                    message.noProxyRegistered = reader.bool();
                    continue;
                case 5:
                    if (tag !== 40) {
                        break;
                    }
                    message.tssSuspended = reader.bool();
                    continue;
                case 6:
                    if (tag !== 48) {
                        break;
                    }
                    message.proxyInsuficientFunds = reader.bool();
                    continue;
                case 7:
                    if (tag !== 56) {
                        break;
                    }
                    message.staleTssHeartbeat = reader.bool();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.QueryValidatorsResponse_TssIllegibilityInfo.$type,
            tombstoned: isSet(object.tombstoned) ? gt.Boolean(object.tombstoned) : false,
            jailed: isSet(object.jailed) ? gt.Boolean(object.jailed) : false,
            missedTooManyBlocks: isSet(object.missedTooManyBlocks) ? gt.Boolean(object.missedTooManyBlocks) : false,
            noProxyRegistered: isSet(object.noProxyRegistered) ? gt.Boolean(object.noProxyRegistered) : false,
            tssSuspended: isSet(object.tssSuspended) ? gt.Boolean(object.tssSuspended) : false,
            proxyInsuficientFunds: isSet(object.proxyInsuficientFunds)
                ? gt.Boolean(object.proxyInsuficientFunds)
                : false,
            staleTssHeartbeat: isSet(object.staleTssHeartbeat) ? gt.Boolean(object.staleTssHeartbeat) : false,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.tombstoned !== false) {
            obj.tombstoned = message.tombstoned;
        }
        if (message.jailed !== false) {
            obj.jailed = message.jailed;
        }
        if (message.missedTooManyBlocks !== false) {
            obj.missedTooManyBlocks = message.missedTooManyBlocks;
        }
        if (message.noProxyRegistered !== false) {
            obj.noProxyRegistered = message.noProxyRegistered;
        }
        if (message.tssSuspended !== false) {
            obj.tssSuspended = message.tssSuspended;
        }
        if (message.proxyInsuficientFunds !== false) {
            obj.proxyInsuficientFunds = message.proxyInsuficientFunds;
        }
        if (message.staleTssHeartbeat !== false) {
            obj.staleTssHeartbeat = message.staleTssHeartbeat;
        }
        return obj;
    },
    create(base) {
        return exports.QueryValidatorsResponse_TssIllegibilityInfo.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b, _c, _d, _e, _f, _g;
        const message = createBaseQueryValidatorsResponse_TssIllegibilityInfo();
        message.tombstoned = (_a = object.tombstoned) !== null && _a !== void 0 ? _a : false;
        message.jailed = (_b = object.jailed) !== null && _b !== void 0 ? _b : false;
        message.missedTooManyBlocks = (_c = object.missedTooManyBlocks) !== null && _c !== void 0 ? _c : false;
        message.noProxyRegistered = (_d = object.noProxyRegistered) !== null && _d !== void 0 ? _d : false;
        message.tssSuspended = (_e = object.tssSuspended) !== null && _e !== void 0 ? _e : false;
        message.proxyInsuficientFunds = (_f = object.proxyInsuficientFunds) !== null && _f !== void 0 ? _f : false;
        message.staleTssHeartbeat = (_g = object.staleTssHeartbeat) !== null && _g !== void 0 ? _g : false;
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.QueryValidatorsResponse_TssIllegibilityInfo.$type, exports.QueryValidatorsResponse_TssIllegibilityInfo);
function createBaseQueryValidatorsResponse_Validator() {
    return {
        $type: "axelar.snapshot.v1beta1.QueryValidatorsResponse.Validator",
        operatorAddress: "",
        moniker: "",
        tssIllegibilityInfo: undefined,
    };
}
exports.QueryValidatorsResponse_Validator = {
    $type: "axelar.snapshot.v1beta1.QueryValidatorsResponse.Validator",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.operatorAddress !== "") {
            writer.uint32(10).string(message.operatorAddress);
        }
        if (message.moniker !== "") {
            writer.uint32(18).string(message.moniker);
        }
        if (message.tssIllegibilityInfo !== undefined) {
            exports.QueryValidatorsResponse_TssIllegibilityInfo.encode(message.tssIllegibilityInfo, writer.uint32(26).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseQueryValidatorsResponse_Validator();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.operatorAddress = reader.string();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.moniker = reader.string();
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.tssIllegibilityInfo = exports.QueryValidatorsResponse_TssIllegibilityInfo.decode(reader, reader.uint32());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.QueryValidatorsResponse_Validator.$type,
            operatorAddress: isSet(object.operatorAddress) ? gt.String(object.operatorAddress) : "",
            moniker: isSet(object.moniker) ? gt.String(object.moniker) : "",
            tssIllegibilityInfo: isSet(object.tssIllegibilityInfo)
                ? exports.QueryValidatorsResponse_TssIllegibilityInfo.fromJSON(object.tssIllegibilityInfo)
                : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.operatorAddress !== "") {
            obj.operatorAddress = message.operatorAddress;
        }
        if (message.moniker !== "") {
            obj.moniker = message.moniker;
        }
        if (message.tssIllegibilityInfo !== undefined) {
            obj.tssIllegibilityInfo = exports.QueryValidatorsResponse_TssIllegibilityInfo.toJSON(message.tssIllegibilityInfo);
        }
        return obj;
    },
    create(base) {
        return exports.QueryValidatorsResponse_Validator.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b;
        const message = createBaseQueryValidatorsResponse_Validator();
        message.operatorAddress = (_a = object.operatorAddress) !== null && _a !== void 0 ? _a : "";
        message.moniker = (_b = object.moniker) !== null && _b !== void 0 ? _b : "";
        message.tssIllegibilityInfo =
            object.tssIllegibilityInfo !== undefined && object.tssIllegibilityInfo !== null
                ? exports.QueryValidatorsResponse_TssIllegibilityInfo.fromPartial(object.tssIllegibilityInfo)
                : undefined;
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.QueryValidatorsResponse_Validator.$type, exports.QueryValidatorsResponse_Validator);
function createBaseParamsRequest() {
    return { $type: "axelar.snapshot.v1beta1.ParamsRequest" };
}
exports.ParamsRequest = {
    $type: "axelar.snapshot.v1beta1.ParamsRequest",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseParamsRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.ParamsRequest.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.ParamsRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseParamsRequest();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.ParamsRequest.$type, exports.ParamsRequest);
function createBaseParamsResponse() {
    return { $type: "axelar.snapshot.v1beta1.ParamsResponse", params: undefined };
}
exports.ParamsResponse = {
    $type: "axelar.snapshot.v1beta1.ParamsResponse",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.params !== undefined) {
            params_1.Params.encode(message.params, writer.uint32(10).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseParamsResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.params = params_1.Params.decode(reader, reader.uint32());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.ParamsResponse.$type,
            params: isSet(object.params) ? params_1.Params.fromJSON(object.params) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.params !== undefined) {
            obj.params = params_1.Params.toJSON(message.params);
        }
        return obj;
    },
    create(base) {
        return exports.ParamsResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        const message = createBaseParamsResponse();
        message.params =
            object.params !== undefined && object.params !== null ? params_1.Params.fromPartial(object.params) : undefined;
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.ParamsResponse.$type, exports.ParamsResponse);
function createBaseOperatorByProxyRequest() {
    return { $type: "axelar.snapshot.v1beta1.OperatorByProxyRequest", proxyAddress: "" };
}
exports.OperatorByProxyRequest = {
    $type: "axelar.snapshot.v1beta1.OperatorByProxyRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.proxyAddress !== "") {
            writer.uint32(10).string(message.proxyAddress);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseOperatorByProxyRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.proxyAddress = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.OperatorByProxyRequest.$type,
            proxyAddress: isSet(object.proxyAddress) ? gt.String(object.proxyAddress) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.proxyAddress !== "") {
            obj.proxyAddress = message.proxyAddress;
        }
        return obj;
    },
    create(base) {
        return exports.OperatorByProxyRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a;
        const message = createBaseOperatorByProxyRequest();
        message.proxyAddress = (_a = object.proxyAddress) !== null && _a !== void 0 ? _a : "";
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.OperatorByProxyRequest.$type, exports.OperatorByProxyRequest);
function createBaseOperatorByProxyResponse() {
    return { $type: "axelar.snapshot.v1beta1.OperatorByProxyResponse", operatorAddress: "" };
}
exports.OperatorByProxyResponse = {
    $type: "axelar.snapshot.v1beta1.OperatorByProxyResponse",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.operatorAddress !== "") {
            writer.uint32(10).string(message.operatorAddress);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseOperatorByProxyResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.operatorAddress = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.OperatorByProxyResponse.$type,
            operatorAddress: isSet(object.operatorAddress) ? gt.String(object.operatorAddress) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.operatorAddress !== "") {
            obj.operatorAddress = message.operatorAddress;
        }
        return obj;
    },
    create(base) {
        return exports.OperatorByProxyResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a;
        const message = createBaseOperatorByProxyResponse();
        message.operatorAddress = (_a = object.operatorAddress) !== null && _a !== void 0 ? _a : "";
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.OperatorByProxyResponse.$type, exports.OperatorByProxyResponse);
function createBaseProxyByOperatorRequest() {
    return { $type: "axelar.snapshot.v1beta1.ProxyByOperatorRequest", operatorAddress: "" };
}
exports.ProxyByOperatorRequest = {
    $type: "axelar.snapshot.v1beta1.ProxyByOperatorRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.operatorAddress !== "") {
            writer.uint32(10).string(message.operatorAddress);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseProxyByOperatorRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.operatorAddress = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.ProxyByOperatorRequest.$type,
            operatorAddress: isSet(object.operatorAddress) ? gt.String(object.operatorAddress) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.operatorAddress !== "") {
            obj.operatorAddress = message.operatorAddress;
        }
        return obj;
    },
    create(base) {
        return exports.ProxyByOperatorRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a;
        const message = createBaseProxyByOperatorRequest();
        message.operatorAddress = (_a = object.operatorAddress) !== null && _a !== void 0 ? _a : "";
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.ProxyByOperatorRequest.$type, exports.ProxyByOperatorRequest);
function createBaseProxyByOperatorResponse() {
    return { $type: "axelar.snapshot.v1beta1.ProxyByOperatorResponse", proxyAddress: "", status: 0 };
}
exports.ProxyByOperatorResponse = {
    $type: "axelar.snapshot.v1beta1.ProxyByOperatorResponse",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.proxyAddress !== "") {
            writer.uint32(10).string(message.proxyAddress);
        }
        if (message.status !== 0) {
            writer.uint32(16).int32(message.status);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseProxyByOperatorResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.proxyAddress = reader.string();
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.status = reader.int32();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.ProxyByOperatorResponse.$type,
            proxyAddress: isSet(object.proxyAddress) ? gt.String(object.proxyAddress) : "",
            status: isSet(object.status) ? proxyByOperatorResponse_StatusFromJSON(object.status) : 0,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.proxyAddress !== "") {
            obj.proxyAddress = message.proxyAddress;
        }
        if (message.status !== 0) {
            obj.status = proxyByOperatorResponse_StatusToJSON(message.status);
        }
        return obj;
    },
    create(base) {
        return exports.ProxyByOperatorResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b;
        const message = createBaseProxyByOperatorResponse();
        message.proxyAddress = (_a = object.proxyAddress) !== null && _a !== void 0 ? _a : "";
        message.status = (_b = object.status) !== null && _b !== void 0 ? _b : 0;
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.ProxyByOperatorResponse.$type, exports.ProxyByOperatorResponse);
const gt = (() => {
    if (typeof globalThis !== "undefined") {
        return globalThis;
    }
    if (typeof self !== "undefined") {
        return self;
    }
    if (typeof window !== "undefined") {
        return window;
    }
    if (typeof global !== "undefined") {
        return global;
    }
    throw "Unable to locate global object";
})();
if (minimal_1.default.util.Long !== long_1.default) {
    minimal_1.default.util.Long = long_1.default;
    minimal_1.default.configure();
}
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=query.js.map