"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.31.1
// source: axelar/multisig/v1beta1/tx.proto
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpdateParamsResponse = exports.UpdateParamsRequest = exports.KeygenOptInResponse = exports.KeygenOptInRequest = exports.KeygenOptOutResponse = exports.KeygenOptOutRequest = exports.RotateKeyResponse = exports.RotateKeyRequest = exports.SubmitSignatureResponse = exports.SubmitSignatureRequest = exports.SubmitPubKeyResponse = exports.SubmitPubKeyRequest = exports.StartKeygenResponse = exports.StartKeygenRequest = exports.protobufPackage = void 0;
/* eslint-disable */
const long_1 = __importDefault(require("long"));
const minimal_1 = __importDefault(require("protobufjs/minimal"));
const typeRegistry_1 = require("../../../typeRegistry");
const params_1 = require("./params");
exports.protobufPackage = "axelar.multisig.v1beta1";
function createBaseStartKeygenRequest() {
    return {
        $type: "axelar.multisig.v1beta1.StartKeygenRequest",
        sender: "",
        keyId: "",
        senderDeprecated: Buffer.alloc(0),
    };
}
exports.StartKeygenRequest = {
    $type: "axelar.multisig.v1beta1.StartKeygenRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.sender !== "") {
            writer.uint32(10).string(message.sender);
        }
        if (message.keyId !== "") {
            writer.uint32(18).string(message.keyId);
        }
        if (message.senderDeprecated.length !== 0) {
            writer.uint32(26).bytes(message.senderDeprecated);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseStartKeygenRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.sender = reader.string();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.keyId = reader.string();
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.senderDeprecated = reader.bytes();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.StartKeygenRequest.$type,
            sender: isSet(object.sender) ? gt.String(object.sender) : "",
            keyId: isSet(object.keyId) ? gt.String(object.keyId) : "",
            senderDeprecated: isSet(object.senderDeprecated)
                ? Buffer.from(bytesFromBase64(object.senderDeprecated))
                : Buffer.alloc(0),
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.sender !== "") {
            obj.sender = message.sender;
        }
        if (message.keyId !== "") {
            obj.keyId = message.keyId;
        }
        if (message.senderDeprecated.length !== 0) {
            obj.senderDeprecated = base64FromBytes(message.senderDeprecated);
        }
        return obj;
    },
    create(base) {
        return exports.StartKeygenRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b, _c;
        const message = createBaseStartKeygenRequest();
        message.sender = (_a = object.sender) !== null && _a !== void 0 ? _a : "";
        message.keyId = (_b = object.keyId) !== null && _b !== void 0 ? _b : "";
        message.senderDeprecated = (_c = object.senderDeprecated) !== null && _c !== void 0 ? _c : Buffer.alloc(0);
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.StartKeygenRequest.$type, exports.StartKeygenRequest);
function createBaseStartKeygenResponse() {
    return { $type: "axelar.multisig.v1beta1.StartKeygenResponse" };
}
exports.StartKeygenResponse = {
    $type: "axelar.multisig.v1beta1.StartKeygenResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseStartKeygenResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.StartKeygenResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.StartKeygenResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseStartKeygenResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.StartKeygenResponse.$type, exports.StartKeygenResponse);
function createBaseSubmitPubKeyRequest() {
    return {
        $type: "axelar.multisig.v1beta1.SubmitPubKeyRequest",
        sender: "",
        keyId: "",
        pubKey: Buffer.alloc(0),
        signature: Buffer.alloc(0),
        senderDeprecated: Buffer.alloc(0),
    };
}
exports.SubmitPubKeyRequest = {
    $type: "axelar.multisig.v1beta1.SubmitPubKeyRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.sender !== "") {
            writer.uint32(10).string(message.sender);
        }
        if (message.keyId !== "") {
            writer.uint32(18).string(message.keyId);
        }
        if (message.pubKey.length !== 0) {
            writer.uint32(26).bytes(message.pubKey);
        }
        if (message.signature.length !== 0) {
            writer.uint32(34).bytes(message.signature);
        }
        if (message.senderDeprecated.length !== 0) {
            writer.uint32(42).bytes(message.senderDeprecated);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSubmitPubKeyRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.sender = reader.string();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.keyId = reader.string();
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.pubKey = reader.bytes();
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.signature = reader.bytes();
                    continue;
                case 5:
                    if (tag !== 42) {
                        break;
                    }
                    message.senderDeprecated = reader.bytes();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.SubmitPubKeyRequest.$type,
            sender: isSet(object.sender) ? gt.String(object.sender) : "",
            keyId: isSet(object.keyId) ? gt.String(object.keyId) : "",
            pubKey: isSet(object.pubKey) ? Buffer.from(bytesFromBase64(object.pubKey)) : Buffer.alloc(0),
            signature: isSet(object.signature) ? Buffer.from(bytesFromBase64(object.signature)) : Buffer.alloc(0),
            senderDeprecated: isSet(object.senderDeprecated)
                ? Buffer.from(bytesFromBase64(object.senderDeprecated))
                : Buffer.alloc(0),
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.sender !== "") {
            obj.sender = message.sender;
        }
        if (message.keyId !== "") {
            obj.keyId = message.keyId;
        }
        if (message.pubKey.length !== 0) {
            obj.pubKey = base64FromBytes(message.pubKey);
        }
        if (message.signature.length !== 0) {
            obj.signature = base64FromBytes(message.signature);
        }
        if (message.senderDeprecated.length !== 0) {
            obj.senderDeprecated = base64FromBytes(message.senderDeprecated);
        }
        return obj;
    },
    create(base) {
        return exports.SubmitPubKeyRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b, _c, _d, _e;
        const message = createBaseSubmitPubKeyRequest();
        message.sender = (_a = object.sender) !== null && _a !== void 0 ? _a : "";
        message.keyId = (_b = object.keyId) !== null && _b !== void 0 ? _b : "";
        message.pubKey = (_c = object.pubKey) !== null && _c !== void 0 ? _c : Buffer.alloc(0);
        message.signature = (_d = object.signature) !== null && _d !== void 0 ? _d : Buffer.alloc(0);
        message.senderDeprecated = (_e = object.senderDeprecated) !== null && _e !== void 0 ? _e : Buffer.alloc(0);
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.SubmitPubKeyRequest.$type, exports.SubmitPubKeyRequest);
function createBaseSubmitPubKeyResponse() {
    return { $type: "axelar.multisig.v1beta1.SubmitPubKeyResponse" };
}
exports.SubmitPubKeyResponse = {
    $type: "axelar.multisig.v1beta1.SubmitPubKeyResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSubmitPubKeyResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.SubmitPubKeyResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.SubmitPubKeyResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseSubmitPubKeyResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.SubmitPubKeyResponse.$type, exports.SubmitPubKeyResponse);
function createBaseSubmitSignatureRequest() {
    return {
        $type: "axelar.multisig.v1beta1.SubmitSignatureRequest",
        sender: "",
        sigId: long_1.default.UZERO,
        signature: Buffer.alloc(0),
        senderDeprecated: Buffer.alloc(0),
    };
}
exports.SubmitSignatureRequest = {
    $type: "axelar.multisig.v1beta1.SubmitSignatureRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.sender !== "") {
            writer.uint32(10).string(message.sender);
        }
        if (!message.sigId.equals(long_1.default.UZERO)) {
            writer.uint32(16).uint64(message.sigId);
        }
        if (message.signature.length !== 0) {
            writer.uint32(26).bytes(message.signature);
        }
        if (message.senderDeprecated.length !== 0) {
            writer.uint32(34).bytes(message.senderDeprecated);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSubmitSignatureRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.sender = reader.string();
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.sigId = reader.uint64();
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.signature = reader.bytes();
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.senderDeprecated = reader.bytes();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.SubmitSignatureRequest.$type,
            sender: isSet(object.sender) ? gt.String(object.sender) : "",
            sigId: isSet(object.sigId) ? long_1.default.fromValue(object.sigId) : long_1.default.UZERO,
            signature: isSet(object.signature) ? Buffer.from(bytesFromBase64(object.signature)) : Buffer.alloc(0),
            senderDeprecated: isSet(object.senderDeprecated)
                ? Buffer.from(bytesFromBase64(object.senderDeprecated))
                : Buffer.alloc(0),
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.sender !== "") {
            obj.sender = message.sender;
        }
        if (!message.sigId.equals(long_1.default.UZERO)) {
            obj.sigId = (message.sigId || long_1.default.UZERO).toString();
        }
        if (message.signature.length !== 0) {
            obj.signature = base64FromBytes(message.signature);
        }
        if (message.senderDeprecated.length !== 0) {
            obj.senderDeprecated = base64FromBytes(message.senderDeprecated);
        }
        return obj;
    },
    create(base) {
        return exports.SubmitSignatureRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b, _c;
        const message = createBaseSubmitSignatureRequest();
        message.sender = (_a = object.sender) !== null && _a !== void 0 ? _a : "";
        message.sigId =
            object.sigId !== undefined && object.sigId !== null ? long_1.default.fromValue(object.sigId) : long_1.default.UZERO;
        message.signature = (_b = object.signature) !== null && _b !== void 0 ? _b : Buffer.alloc(0);
        message.senderDeprecated = (_c = object.senderDeprecated) !== null && _c !== void 0 ? _c : Buffer.alloc(0);
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.SubmitSignatureRequest.$type, exports.SubmitSignatureRequest);
function createBaseSubmitSignatureResponse() {
    return { $type: "axelar.multisig.v1beta1.SubmitSignatureResponse" };
}
exports.SubmitSignatureResponse = {
    $type: "axelar.multisig.v1beta1.SubmitSignatureResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSubmitSignatureResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.SubmitSignatureResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.SubmitSignatureResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseSubmitSignatureResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.SubmitSignatureResponse.$type, exports.SubmitSignatureResponse);
function createBaseRotateKeyRequest() {
    return {
        $type: "axelar.multisig.v1beta1.RotateKeyRequest",
        sender: "",
        chain: "",
        keyId: "",
        senderDeprecated: Buffer.alloc(0),
    };
}
exports.RotateKeyRequest = {
    $type: "axelar.multisig.v1beta1.RotateKeyRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.sender !== "") {
            writer.uint32(10).string(message.sender);
        }
        if (message.chain !== "") {
            writer.uint32(18).string(message.chain);
        }
        if (message.keyId !== "") {
            writer.uint32(26).string(message.keyId);
        }
        if (message.senderDeprecated.length !== 0) {
            writer.uint32(34).bytes(message.senderDeprecated);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRotateKeyRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.sender = reader.string();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.chain = reader.string();
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.keyId = reader.string();
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.senderDeprecated = reader.bytes();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.RotateKeyRequest.$type,
            sender: isSet(object.sender) ? gt.String(object.sender) : "",
            chain: isSet(object.chain) ? gt.String(object.chain) : "",
            keyId: isSet(object.keyId) ? gt.String(object.keyId) : "",
            senderDeprecated: isSet(object.senderDeprecated)
                ? Buffer.from(bytesFromBase64(object.senderDeprecated))
                : Buffer.alloc(0),
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.sender !== "") {
            obj.sender = message.sender;
        }
        if (message.chain !== "") {
            obj.chain = message.chain;
        }
        if (message.keyId !== "") {
            obj.keyId = message.keyId;
        }
        if (message.senderDeprecated.length !== 0) {
            obj.senderDeprecated = base64FromBytes(message.senderDeprecated);
        }
        return obj;
    },
    create(base) {
        return exports.RotateKeyRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b, _c, _d;
        const message = createBaseRotateKeyRequest();
        message.sender = (_a = object.sender) !== null && _a !== void 0 ? _a : "";
        message.chain = (_b = object.chain) !== null && _b !== void 0 ? _b : "";
        message.keyId = (_c = object.keyId) !== null && _c !== void 0 ? _c : "";
        message.senderDeprecated = (_d = object.senderDeprecated) !== null && _d !== void 0 ? _d : Buffer.alloc(0);
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.RotateKeyRequest.$type, exports.RotateKeyRequest);
function createBaseRotateKeyResponse() {
    return { $type: "axelar.multisig.v1beta1.RotateKeyResponse" };
}
exports.RotateKeyResponse = {
    $type: "axelar.multisig.v1beta1.RotateKeyResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRotateKeyResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.RotateKeyResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.RotateKeyResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseRotateKeyResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.RotateKeyResponse.$type, exports.RotateKeyResponse);
function createBaseKeygenOptOutRequest() {
    return {
        $type: "axelar.multisig.v1beta1.KeygenOptOutRequest",
        senderDeprecated: Buffer.alloc(0),
        sender: "",
    };
}
exports.KeygenOptOutRequest = {
    $type: "axelar.multisig.v1beta1.KeygenOptOutRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.senderDeprecated.length !== 0) {
            writer.uint32(10).bytes(message.senderDeprecated);
        }
        if (message.sender !== "") {
            writer.uint32(18).string(message.sender);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseKeygenOptOutRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.senderDeprecated = reader.bytes();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.sender = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.KeygenOptOutRequest.$type,
            senderDeprecated: isSet(object.senderDeprecated)
                ? Buffer.from(bytesFromBase64(object.senderDeprecated))
                : Buffer.alloc(0),
            sender: isSet(object.sender) ? gt.String(object.sender) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.senderDeprecated.length !== 0) {
            obj.senderDeprecated = base64FromBytes(message.senderDeprecated);
        }
        if (message.sender !== "") {
            obj.sender = message.sender;
        }
        return obj;
    },
    create(base) {
        return exports.KeygenOptOutRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b;
        const message = createBaseKeygenOptOutRequest();
        message.senderDeprecated = (_a = object.senderDeprecated) !== null && _a !== void 0 ? _a : Buffer.alloc(0);
        message.sender = (_b = object.sender) !== null && _b !== void 0 ? _b : "";
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.KeygenOptOutRequest.$type, exports.KeygenOptOutRequest);
function createBaseKeygenOptOutResponse() {
    return { $type: "axelar.multisig.v1beta1.KeygenOptOutResponse" };
}
exports.KeygenOptOutResponse = {
    $type: "axelar.multisig.v1beta1.KeygenOptOutResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseKeygenOptOutResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.KeygenOptOutResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.KeygenOptOutResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseKeygenOptOutResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.KeygenOptOutResponse.$type, exports.KeygenOptOutResponse);
function createBaseKeygenOptInRequest() {
    return {
        $type: "axelar.multisig.v1beta1.KeygenOptInRequest",
        senderDeprecated: Buffer.alloc(0),
        sender: "",
    };
}
exports.KeygenOptInRequest = {
    $type: "axelar.multisig.v1beta1.KeygenOptInRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.senderDeprecated.length !== 0) {
            writer.uint32(10).bytes(message.senderDeprecated);
        }
        if (message.sender !== "") {
            writer.uint32(18).string(message.sender);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseKeygenOptInRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.senderDeprecated = reader.bytes();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.sender = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.KeygenOptInRequest.$type,
            senderDeprecated: isSet(object.senderDeprecated)
                ? Buffer.from(bytesFromBase64(object.senderDeprecated))
                : Buffer.alloc(0),
            sender: isSet(object.sender) ? gt.String(object.sender) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.senderDeprecated.length !== 0) {
            obj.senderDeprecated = base64FromBytes(message.senderDeprecated);
        }
        if (message.sender !== "") {
            obj.sender = message.sender;
        }
        return obj;
    },
    create(base) {
        return exports.KeygenOptInRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b;
        const message = createBaseKeygenOptInRequest();
        message.senderDeprecated = (_a = object.senderDeprecated) !== null && _a !== void 0 ? _a : Buffer.alloc(0);
        message.sender = (_b = object.sender) !== null && _b !== void 0 ? _b : "";
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.KeygenOptInRequest.$type, exports.KeygenOptInRequest);
function createBaseKeygenOptInResponse() {
    return { $type: "axelar.multisig.v1beta1.KeygenOptInResponse" };
}
exports.KeygenOptInResponse = {
    $type: "axelar.multisig.v1beta1.KeygenOptInResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseKeygenOptInResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.KeygenOptInResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.KeygenOptInResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseKeygenOptInResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.KeygenOptInResponse.$type, exports.KeygenOptInResponse);
function createBaseUpdateParamsRequest() {
    return { $type: "axelar.multisig.v1beta1.UpdateParamsRequest", authority: "", params: undefined };
}
exports.UpdateParamsRequest = {
    $type: "axelar.multisig.v1beta1.UpdateParamsRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.authority !== "") {
            writer.uint32(10).string(message.authority);
        }
        if (message.params !== undefined) {
            params_1.Params.encode(message.params, writer.uint32(18).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseUpdateParamsRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.authority = reader.string();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.params = params_1.Params.decode(reader, reader.uint32());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.UpdateParamsRequest.$type,
            authority: isSet(object.authority) ? gt.String(object.authority) : "",
            params: isSet(object.params) ? params_1.Params.fromJSON(object.params) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.authority !== "") {
            obj.authority = message.authority;
        }
        if (message.params !== undefined) {
            obj.params = params_1.Params.toJSON(message.params);
        }
        return obj;
    },
    create(base) {
        return exports.UpdateParamsRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a;
        const message = createBaseUpdateParamsRequest();
        message.authority = (_a = object.authority) !== null && _a !== void 0 ? _a : "";
        message.params =
            object.params !== undefined && object.params !== null ? params_1.Params.fromPartial(object.params) : undefined;
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.UpdateParamsRequest.$type, exports.UpdateParamsRequest);
function createBaseUpdateParamsResponse() {
    return { $type: "axelar.multisig.v1beta1.UpdateParamsResponse" };
}
exports.UpdateParamsResponse = {
    $type: "axelar.multisig.v1beta1.UpdateParamsResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseUpdateParamsResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.UpdateParamsResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.UpdateParamsResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseUpdateParamsResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.UpdateParamsResponse.$type, exports.UpdateParamsResponse);
const gt = (() => {
    if (typeof globalThis !== "undefined") {
        return globalThis;
    }
    if (typeof self !== "undefined") {
        return self;
    }
    if (typeof window !== "undefined") {
        return window;
    }
    if (typeof global !== "undefined") {
        return global;
    }
    throw "Unable to locate global object";
})();
function bytesFromBase64(b64) {
    return Uint8Array.from(gt.Buffer.from(b64, "base64"));
}
function base64FromBytes(arr) {
    return gt.Buffer.from(arr).toString("base64");
}
if (minimal_1.default.util.Long !== long_1.default) {
    minimal_1.default.util.Long = long_1.default;
    minimal_1.default.configure();
}
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=tx.js.map