"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.33.4
// source: axelar/axelarnet/v1beta1/tx.proto
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpdateParamsResponse = exports.UpdateParamsRequest = exports.CallContractResponse = exports.CallContractRequest = exports.RouteMessageResponse = exports.RouteMessageRequest = exports.RetryIBCTransferResponse = exports.RetryIBCTransferRequest = exports.RegisterFeeCollectorResponse = exports.RegisterFeeCollectorRequest = exports.RouteIBCTransfersResponse = exports.RouteIBCTransfersRequest = exports.RegisterAssetResponse = exports.RegisterAssetRequest = exports.AddCosmosBasedChainResponse = exports.AddCosmosBasedChainRequest = exports.RegisterIBCPathResponse = exports.RegisterIBCPathRequest = exports.ExecutePendingTransfersResponse = exports.ExecutePendingTransfersRequest = exports.ConfirmDepositResponse = exports.ConfirmDepositRequest = exports.LinkResponse = exports.LinkRequest = exports.protobufPackage = void 0;
/* eslint-disable */
const long_1 = __importDefault(require("long"));
const minimal_1 = __importDefault(require("protobufjs/minimal"));
const coin_1 = require("../../../cosmos/base/v1beta1/coin");
const duration_1 = require("../../../google/protobuf/duration");
const typeRegistry_1 = require("../../../typeRegistry");
const types_1 = require("../../nexus/exported/v1beta1/types");
const params_1 = require("./params");
const types_2 = require("./types");
exports.protobufPackage = "axelar.axelarnet.v1beta1";
function createBaseLinkRequest() {
    return {
        $type: "axelar.axelarnet.v1beta1.LinkRequest",
        senderDeprecated: Buffer.alloc(0),
        recipientAddr: "",
        recipientChain: "",
        asset: "",
        sender: "",
    };
}
exports.LinkRequest = {
    $type: "axelar.axelarnet.v1beta1.LinkRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.senderDeprecated.length !== 0) {
            writer.uint32(10).bytes(message.senderDeprecated);
        }
        if (message.recipientAddr !== "") {
            writer.uint32(18).string(message.recipientAddr);
        }
        if (message.recipientChain !== "") {
            writer.uint32(26).string(message.recipientChain);
        }
        if (message.asset !== "") {
            writer.uint32(34).string(message.asset);
        }
        if (message.sender !== "") {
            writer.uint32(42).string(message.sender);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseLinkRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.senderDeprecated = reader.bytes();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.recipientAddr = reader.string();
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.recipientChain = reader.string();
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.asset = reader.string();
                    continue;
                case 5:
                    if (tag !== 42) {
                        break;
                    }
                    message.sender = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.LinkRequest.$type,
            senderDeprecated: isSet(object.senderDeprecated)
                ? Buffer.from(bytesFromBase64(object.senderDeprecated))
                : Buffer.alloc(0),
            recipientAddr: isSet(object.recipientAddr) ? gt.String(object.recipientAddr) : "",
            recipientChain: isSet(object.recipientChain) ? gt.String(object.recipientChain) : "",
            asset: isSet(object.asset) ? gt.String(object.asset) : "",
            sender: isSet(object.sender) ? gt.String(object.sender) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.senderDeprecated.length !== 0) {
            obj.senderDeprecated = base64FromBytes(message.senderDeprecated);
        }
        if (message.recipientAddr !== "") {
            obj.recipientAddr = message.recipientAddr;
        }
        if (message.recipientChain !== "") {
            obj.recipientChain = message.recipientChain;
        }
        if (message.asset !== "") {
            obj.asset = message.asset;
        }
        if (message.sender !== "") {
            obj.sender = message.sender;
        }
        return obj;
    },
    create(base) {
        return exports.LinkRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b, _c, _d, _e;
        const message = createBaseLinkRequest();
        message.senderDeprecated = (_a = object.senderDeprecated) !== null && _a !== void 0 ? _a : Buffer.alloc(0);
        message.recipientAddr = (_b = object.recipientAddr) !== null && _b !== void 0 ? _b : "";
        message.recipientChain = (_c = object.recipientChain) !== null && _c !== void 0 ? _c : "";
        message.asset = (_d = object.asset) !== null && _d !== void 0 ? _d : "";
        message.sender = (_e = object.sender) !== null && _e !== void 0 ? _e : "";
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.LinkRequest.$type, exports.LinkRequest);
function createBaseLinkResponse() {
    return { $type: "axelar.axelarnet.v1beta1.LinkResponse", depositAddr: "" };
}
exports.LinkResponse = {
    $type: "axelar.axelarnet.v1beta1.LinkResponse",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.depositAddr !== "") {
            writer.uint32(10).string(message.depositAddr);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseLinkResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.depositAddr = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.LinkResponse.$type,
            depositAddr: isSet(object.depositAddr) ? gt.String(object.depositAddr) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.depositAddr !== "") {
            obj.depositAddr = message.depositAddr;
        }
        return obj;
    },
    create(base) {
        return exports.LinkResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a;
        const message = createBaseLinkResponse();
        message.depositAddr = (_a = object.depositAddr) !== null && _a !== void 0 ? _a : "";
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.LinkResponse.$type, exports.LinkResponse);
function createBaseConfirmDepositRequest() {
    return {
        $type: "axelar.axelarnet.v1beta1.ConfirmDepositRequest",
        senderDeprecated: Buffer.alloc(0),
        txIdDeprecated: Buffer.alloc(0),
        tokenDeprecated: undefined,
        depositAddress: Buffer.alloc(0),
        denom: "",
        sender: "",
    };
}
exports.ConfirmDepositRequest = {
    $type: "axelar.axelarnet.v1beta1.ConfirmDepositRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.senderDeprecated.length !== 0) {
            writer.uint32(10).bytes(message.senderDeprecated);
        }
        if (message.txIdDeprecated.length !== 0) {
            writer.uint32(18).bytes(message.txIdDeprecated);
        }
        if (message.tokenDeprecated !== undefined) {
            coin_1.Coin.encode(message.tokenDeprecated, writer.uint32(26).fork()).ldelim();
        }
        if (message.depositAddress.length !== 0) {
            writer.uint32(34).bytes(message.depositAddress);
        }
        if (message.denom !== "") {
            writer.uint32(42).string(message.denom);
        }
        if (message.sender !== "") {
            writer.uint32(50).string(message.sender);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseConfirmDepositRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.senderDeprecated = reader.bytes();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.txIdDeprecated = reader.bytes();
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.tokenDeprecated = coin_1.Coin.decode(reader, reader.uint32());
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.depositAddress = reader.bytes();
                    continue;
                case 5:
                    if (tag !== 42) {
                        break;
                    }
                    message.denom = reader.string();
                    continue;
                case 6:
                    if (tag !== 50) {
                        break;
                    }
                    message.sender = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.ConfirmDepositRequest.$type,
            senderDeprecated: isSet(object.senderDeprecated)
                ? Buffer.from(bytesFromBase64(object.senderDeprecated))
                : Buffer.alloc(0),
            txIdDeprecated: isSet(object.txIdDeprecated)
                ? Buffer.from(bytesFromBase64(object.txIdDeprecated))
                : Buffer.alloc(0),
            tokenDeprecated: isSet(object.tokenDeprecated) ? coin_1.Coin.fromJSON(object.tokenDeprecated) : undefined,
            depositAddress: isSet(object.depositAddress)
                ? Buffer.from(bytesFromBase64(object.depositAddress))
                : Buffer.alloc(0),
            denom: isSet(object.denom) ? gt.String(object.denom) : "",
            sender: isSet(object.sender) ? gt.String(object.sender) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.senderDeprecated.length !== 0) {
            obj.senderDeprecated = base64FromBytes(message.senderDeprecated);
        }
        if (message.txIdDeprecated.length !== 0) {
            obj.txIdDeprecated = base64FromBytes(message.txIdDeprecated);
        }
        if (message.tokenDeprecated !== undefined) {
            obj.tokenDeprecated = coin_1.Coin.toJSON(message.tokenDeprecated);
        }
        if (message.depositAddress.length !== 0) {
            obj.depositAddress = base64FromBytes(message.depositAddress);
        }
        if (message.denom !== "") {
            obj.denom = message.denom;
        }
        if (message.sender !== "") {
            obj.sender = message.sender;
        }
        return obj;
    },
    create(base) {
        return exports.ConfirmDepositRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b, _c, _d, _e;
        const message = createBaseConfirmDepositRequest();
        message.senderDeprecated = (_a = object.senderDeprecated) !== null && _a !== void 0 ? _a : Buffer.alloc(0);
        message.txIdDeprecated = (_b = object.txIdDeprecated) !== null && _b !== void 0 ? _b : Buffer.alloc(0);
        message.tokenDeprecated =
            object.tokenDeprecated !== undefined && object.tokenDeprecated !== null
                ? coin_1.Coin.fromPartial(object.tokenDeprecated)
                : undefined;
        message.depositAddress = (_c = object.depositAddress) !== null && _c !== void 0 ? _c : Buffer.alloc(0);
        message.denom = (_d = object.denom) !== null && _d !== void 0 ? _d : "";
        message.sender = (_e = object.sender) !== null && _e !== void 0 ? _e : "";
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.ConfirmDepositRequest.$type, exports.ConfirmDepositRequest);
function createBaseConfirmDepositResponse() {
    return { $type: "axelar.axelarnet.v1beta1.ConfirmDepositResponse" };
}
exports.ConfirmDepositResponse = {
    $type: "axelar.axelarnet.v1beta1.ConfirmDepositResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseConfirmDepositResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.ConfirmDepositResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.ConfirmDepositResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseConfirmDepositResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.ConfirmDepositResponse.$type, exports.ConfirmDepositResponse);
function createBaseExecutePendingTransfersRequest() {
    return {
        $type: "axelar.axelarnet.v1beta1.ExecutePendingTransfersRequest",
        senderDeprecated: Buffer.alloc(0),
        sender: "",
    };
}
exports.ExecutePendingTransfersRequest = {
    $type: "axelar.axelarnet.v1beta1.ExecutePendingTransfersRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.senderDeprecated.length !== 0) {
            writer.uint32(10).bytes(message.senderDeprecated);
        }
        if (message.sender !== "") {
            writer.uint32(18).string(message.sender);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseExecutePendingTransfersRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.senderDeprecated = reader.bytes();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.sender = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.ExecutePendingTransfersRequest.$type,
            senderDeprecated: isSet(object.senderDeprecated)
                ? Buffer.from(bytesFromBase64(object.senderDeprecated))
                : Buffer.alloc(0),
            sender: isSet(object.sender) ? gt.String(object.sender) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.senderDeprecated.length !== 0) {
            obj.senderDeprecated = base64FromBytes(message.senderDeprecated);
        }
        if (message.sender !== "") {
            obj.sender = message.sender;
        }
        return obj;
    },
    create(base) {
        return exports.ExecutePendingTransfersRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b;
        const message = createBaseExecutePendingTransfersRequest();
        message.senderDeprecated = (_a = object.senderDeprecated) !== null && _a !== void 0 ? _a : Buffer.alloc(0);
        message.sender = (_b = object.sender) !== null && _b !== void 0 ? _b : "";
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.ExecutePendingTransfersRequest.$type, exports.ExecutePendingTransfersRequest);
function createBaseExecutePendingTransfersResponse() {
    return { $type: "axelar.axelarnet.v1beta1.ExecutePendingTransfersResponse" };
}
exports.ExecutePendingTransfersResponse = {
    $type: "axelar.axelarnet.v1beta1.ExecutePendingTransfersResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseExecutePendingTransfersResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.ExecutePendingTransfersResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.ExecutePendingTransfersResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseExecutePendingTransfersResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.ExecutePendingTransfersResponse.$type, exports.ExecutePendingTransfersResponse);
function createBaseRegisterIBCPathRequest() {
    return {
        $type: "axelar.axelarnet.v1beta1.RegisterIBCPathRequest",
        senderDeprecated: Buffer.alloc(0),
        chain: "",
        path: "",
        sender: "",
    };
}
exports.RegisterIBCPathRequest = {
    $type: "axelar.axelarnet.v1beta1.RegisterIBCPathRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.senderDeprecated.length !== 0) {
            writer.uint32(10).bytes(message.senderDeprecated);
        }
        if (message.chain !== "") {
            writer.uint32(18).string(message.chain);
        }
        if (message.path !== "") {
            writer.uint32(26).string(message.path);
        }
        if (message.sender !== "") {
            writer.uint32(34).string(message.sender);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRegisterIBCPathRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.senderDeprecated = reader.bytes();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.chain = reader.string();
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.path = reader.string();
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.sender = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.RegisterIBCPathRequest.$type,
            senderDeprecated: isSet(object.senderDeprecated)
                ? Buffer.from(bytesFromBase64(object.senderDeprecated))
                : Buffer.alloc(0),
            chain: isSet(object.chain) ? gt.String(object.chain) : "",
            path: isSet(object.path) ? gt.String(object.path) : "",
            sender: isSet(object.sender) ? gt.String(object.sender) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.senderDeprecated.length !== 0) {
            obj.senderDeprecated = base64FromBytes(message.senderDeprecated);
        }
        if (message.chain !== "") {
            obj.chain = message.chain;
        }
        if (message.path !== "") {
            obj.path = message.path;
        }
        if (message.sender !== "") {
            obj.sender = message.sender;
        }
        return obj;
    },
    create(base) {
        return exports.RegisterIBCPathRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b, _c, _d;
        const message = createBaseRegisterIBCPathRequest();
        message.senderDeprecated = (_a = object.senderDeprecated) !== null && _a !== void 0 ? _a : Buffer.alloc(0);
        message.chain = (_b = object.chain) !== null && _b !== void 0 ? _b : "";
        message.path = (_c = object.path) !== null && _c !== void 0 ? _c : "";
        message.sender = (_d = object.sender) !== null && _d !== void 0 ? _d : "";
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.RegisterIBCPathRequest.$type, exports.RegisterIBCPathRequest);
function createBaseRegisterIBCPathResponse() {
    return { $type: "axelar.axelarnet.v1beta1.RegisterIBCPathResponse" };
}
exports.RegisterIBCPathResponse = {
    $type: "axelar.axelarnet.v1beta1.RegisterIBCPathResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRegisterIBCPathResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.RegisterIBCPathResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.RegisterIBCPathResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseRegisterIBCPathResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.RegisterIBCPathResponse.$type, exports.RegisterIBCPathResponse);
function createBaseAddCosmosBasedChainRequest() {
    return {
        $type: "axelar.axelarnet.v1beta1.AddCosmosBasedChainRequest",
        senderDeprecated: Buffer.alloc(0),
        chain: undefined,
        addrPrefix: "",
        minAmountDeprecated: Buffer.alloc(0),
        nativeAssets: [],
        cosmosChain: "",
        ibcPath: "",
        sender: "",
    };
}
exports.AddCosmosBasedChainRequest = {
    $type: "axelar.axelarnet.v1beta1.AddCosmosBasedChainRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.senderDeprecated.length !== 0) {
            writer.uint32(10).bytes(message.senderDeprecated);
        }
        if (message.chain !== undefined) {
            types_1.Chain.encode(message.chain, writer.uint32(18).fork()).ldelim();
        }
        if (message.addrPrefix !== "") {
            writer.uint32(26).string(message.addrPrefix);
        }
        if (message.minAmountDeprecated.length !== 0) {
            writer.uint32(34).bytes(message.minAmountDeprecated);
        }
        for (const v of message.nativeAssets) {
            types_1.Asset.encode(v, writer.uint32(42).fork()).ldelim();
        }
        if (message.cosmosChain !== "") {
            writer.uint32(50).string(message.cosmosChain);
        }
        if (message.ibcPath !== "") {
            writer.uint32(58).string(message.ibcPath);
        }
        if (message.sender !== "") {
            writer.uint32(66).string(message.sender);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseAddCosmosBasedChainRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.senderDeprecated = reader.bytes();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.chain = types_1.Chain.decode(reader, reader.uint32());
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.addrPrefix = reader.string();
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.minAmountDeprecated = reader.bytes();
                    continue;
                case 5:
                    if (tag !== 42) {
                        break;
                    }
                    message.nativeAssets.push(types_1.Asset.decode(reader, reader.uint32()));
                    continue;
                case 6:
                    if (tag !== 50) {
                        break;
                    }
                    message.cosmosChain = reader.string();
                    continue;
                case 7:
                    if (tag !== 58) {
                        break;
                    }
                    message.ibcPath = reader.string();
                    continue;
                case 8:
                    if (tag !== 66) {
                        break;
                    }
                    message.sender = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.AddCosmosBasedChainRequest.$type,
            senderDeprecated: isSet(object.senderDeprecated)
                ? Buffer.from(bytesFromBase64(object.senderDeprecated))
                : Buffer.alloc(0),
            chain: isSet(object.chain) ? types_1.Chain.fromJSON(object.chain) : undefined,
            addrPrefix: isSet(object.addrPrefix) ? gt.String(object.addrPrefix) : "",
            minAmountDeprecated: isSet(object.minAmountDeprecated)
                ? Buffer.from(bytesFromBase64(object.minAmountDeprecated))
                : Buffer.alloc(0),
            nativeAssets: gt.Array.isArray(object === null || object === void 0 ? void 0 : object.nativeAssets)
                ? object.nativeAssets.map((e) => types_1.Asset.fromJSON(e))
                : [],
            cosmosChain: isSet(object.cosmosChain) ? gt.String(object.cosmosChain) : "",
            ibcPath: isSet(object.ibcPath) ? gt.String(object.ibcPath) : "",
            sender: isSet(object.sender) ? gt.String(object.sender) : "",
        };
    },
    toJSON(message) {
        var _a;
        const obj = {};
        if (message.senderDeprecated.length !== 0) {
            obj.senderDeprecated = base64FromBytes(message.senderDeprecated);
        }
        if (message.chain !== undefined) {
            obj.chain = types_1.Chain.toJSON(message.chain);
        }
        if (message.addrPrefix !== "") {
            obj.addrPrefix = message.addrPrefix;
        }
        if (message.minAmountDeprecated.length !== 0) {
            obj.minAmountDeprecated = base64FromBytes(message.minAmountDeprecated);
        }
        if ((_a = message.nativeAssets) === null || _a === void 0 ? void 0 : _a.length) {
            obj.nativeAssets = message.nativeAssets.map((e) => types_1.Asset.toJSON(e));
        }
        if (message.cosmosChain !== "") {
            obj.cosmosChain = message.cosmosChain;
        }
        if (message.ibcPath !== "") {
            obj.ibcPath = message.ibcPath;
        }
        if (message.sender !== "") {
            obj.sender = message.sender;
        }
        return obj;
    },
    create(base) {
        return exports.AddCosmosBasedChainRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b, _c, _d, _e, _f, _g;
        const message = createBaseAddCosmosBasedChainRequest();
        message.senderDeprecated = (_a = object.senderDeprecated) !== null && _a !== void 0 ? _a : Buffer.alloc(0);
        message.chain =
            object.chain !== undefined && object.chain !== null ? types_1.Chain.fromPartial(object.chain) : undefined;
        message.addrPrefix = (_b = object.addrPrefix) !== null && _b !== void 0 ? _b : "";
        message.minAmountDeprecated = (_c = object.minAmountDeprecated) !== null && _c !== void 0 ? _c : Buffer.alloc(0);
        message.nativeAssets = ((_d = object.nativeAssets) === null || _d === void 0 ? void 0 : _d.map((e) => types_1.Asset.fromPartial(e))) || [];
        message.cosmosChain = (_e = object.cosmosChain) !== null && _e !== void 0 ? _e : "";
        message.ibcPath = (_f = object.ibcPath) !== null && _f !== void 0 ? _f : "";
        message.sender = (_g = object.sender) !== null && _g !== void 0 ? _g : "";
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.AddCosmosBasedChainRequest.$type, exports.AddCosmosBasedChainRequest);
function createBaseAddCosmosBasedChainResponse() {
    return { $type: "axelar.axelarnet.v1beta1.AddCosmosBasedChainResponse" };
}
exports.AddCosmosBasedChainResponse = {
    $type: "axelar.axelarnet.v1beta1.AddCosmosBasedChainResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseAddCosmosBasedChainResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.AddCosmosBasedChainResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.AddCosmosBasedChainResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseAddCosmosBasedChainResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.AddCosmosBasedChainResponse.$type, exports.AddCosmosBasedChainResponse);
function createBaseRegisterAssetRequest() {
    return {
        $type: "axelar.axelarnet.v1beta1.RegisterAssetRequest",
        senderDeprecated: Buffer.alloc(0),
        chain: "",
        asset: undefined,
        limit: Buffer.alloc(0),
        window: undefined,
        sender: "",
    };
}
exports.RegisterAssetRequest = {
    $type: "axelar.axelarnet.v1beta1.RegisterAssetRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.senderDeprecated.length !== 0) {
            writer.uint32(10).bytes(message.senderDeprecated);
        }
        if (message.chain !== "") {
            writer.uint32(18).string(message.chain);
        }
        if (message.asset !== undefined) {
            types_1.Asset.encode(message.asset, writer.uint32(26).fork()).ldelim();
        }
        if (message.limit.length !== 0) {
            writer.uint32(34).bytes(message.limit);
        }
        if (message.window !== undefined) {
            duration_1.Duration.encode(message.window, writer.uint32(42).fork()).ldelim();
        }
        if (message.sender !== "") {
            writer.uint32(50).string(message.sender);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRegisterAssetRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.senderDeprecated = reader.bytes();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.chain = reader.string();
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.asset = types_1.Asset.decode(reader, reader.uint32());
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.limit = reader.bytes();
                    continue;
                case 5:
                    if (tag !== 42) {
                        break;
                    }
                    message.window = duration_1.Duration.decode(reader, reader.uint32());
                    continue;
                case 6:
                    if (tag !== 50) {
                        break;
                    }
                    message.sender = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.RegisterAssetRequest.$type,
            senderDeprecated: isSet(object.senderDeprecated)
                ? Buffer.from(bytesFromBase64(object.senderDeprecated))
                : Buffer.alloc(0),
            chain: isSet(object.chain) ? gt.String(object.chain) : "",
            asset: isSet(object.asset) ? types_1.Asset.fromJSON(object.asset) : undefined,
            limit: isSet(object.limit) ? Buffer.from(bytesFromBase64(object.limit)) : Buffer.alloc(0),
            window: isSet(object.window) ? duration_1.Duration.fromJSON(object.window) : undefined,
            sender: isSet(object.sender) ? gt.String(object.sender) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.senderDeprecated.length !== 0) {
            obj.senderDeprecated = base64FromBytes(message.senderDeprecated);
        }
        if (message.chain !== "") {
            obj.chain = message.chain;
        }
        if (message.asset !== undefined) {
            obj.asset = types_1.Asset.toJSON(message.asset);
        }
        if (message.limit.length !== 0) {
            obj.limit = base64FromBytes(message.limit);
        }
        if (message.window !== undefined) {
            obj.window = duration_1.Duration.toJSON(message.window);
        }
        if (message.sender !== "") {
            obj.sender = message.sender;
        }
        return obj;
    },
    create(base) {
        return exports.RegisterAssetRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b, _c, _d;
        const message = createBaseRegisterAssetRequest();
        message.senderDeprecated = (_a = object.senderDeprecated) !== null && _a !== void 0 ? _a : Buffer.alloc(0);
        message.chain = (_b = object.chain) !== null && _b !== void 0 ? _b : "";
        message.asset =
            object.asset !== undefined && object.asset !== null ? types_1.Asset.fromPartial(object.asset) : undefined;
        message.limit = (_c = object.limit) !== null && _c !== void 0 ? _c : Buffer.alloc(0);
        message.window =
            object.window !== undefined && object.window !== null ? duration_1.Duration.fromPartial(object.window) : undefined;
        message.sender = (_d = object.sender) !== null && _d !== void 0 ? _d : "";
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.RegisterAssetRequest.$type, exports.RegisterAssetRequest);
function createBaseRegisterAssetResponse() {
    return { $type: "axelar.axelarnet.v1beta1.RegisterAssetResponse" };
}
exports.RegisterAssetResponse = {
    $type: "axelar.axelarnet.v1beta1.RegisterAssetResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRegisterAssetResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.RegisterAssetResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.RegisterAssetResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseRegisterAssetResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.RegisterAssetResponse.$type, exports.RegisterAssetResponse);
function createBaseRouteIBCTransfersRequest() {
    return {
        $type: "axelar.axelarnet.v1beta1.RouteIBCTransfersRequest",
        senderDeprecated: Buffer.alloc(0),
        sender: "",
    };
}
exports.RouteIBCTransfersRequest = {
    $type: "axelar.axelarnet.v1beta1.RouteIBCTransfersRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.senderDeprecated.length !== 0) {
            writer.uint32(10).bytes(message.senderDeprecated);
        }
        if (message.sender !== "") {
            writer.uint32(18).string(message.sender);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRouteIBCTransfersRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.senderDeprecated = reader.bytes();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.sender = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.RouteIBCTransfersRequest.$type,
            senderDeprecated: isSet(object.senderDeprecated)
                ? Buffer.from(bytesFromBase64(object.senderDeprecated))
                : Buffer.alloc(0),
            sender: isSet(object.sender) ? gt.String(object.sender) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.senderDeprecated.length !== 0) {
            obj.senderDeprecated = base64FromBytes(message.senderDeprecated);
        }
        if (message.sender !== "") {
            obj.sender = message.sender;
        }
        return obj;
    },
    create(base) {
        return exports.RouteIBCTransfersRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b;
        const message = createBaseRouteIBCTransfersRequest();
        message.senderDeprecated = (_a = object.senderDeprecated) !== null && _a !== void 0 ? _a : Buffer.alloc(0);
        message.sender = (_b = object.sender) !== null && _b !== void 0 ? _b : "";
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.RouteIBCTransfersRequest.$type, exports.RouteIBCTransfersRequest);
function createBaseRouteIBCTransfersResponse() {
    return { $type: "axelar.axelarnet.v1beta1.RouteIBCTransfersResponse" };
}
exports.RouteIBCTransfersResponse = {
    $type: "axelar.axelarnet.v1beta1.RouteIBCTransfersResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRouteIBCTransfersResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.RouteIBCTransfersResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.RouteIBCTransfersResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseRouteIBCTransfersResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.RouteIBCTransfersResponse.$type, exports.RouteIBCTransfersResponse);
function createBaseRegisterFeeCollectorRequest() {
    return {
        $type: "axelar.axelarnet.v1beta1.RegisterFeeCollectorRequest",
        senderDeprecated: Buffer.alloc(0),
        feeCollector: Buffer.alloc(0),
        sender: "",
    };
}
exports.RegisterFeeCollectorRequest = {
    $type: "axelar.axelarnet.v1beta1.RegisterFeeCollectorRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.senderDeprecated.length !== 0) {
            writer.uint32(10).bytes(message.senderDeprecated);
        }
        if (message.feeCollector.length !== 0) {
            writer.uint32(18).bytes(message.feeCollector);
        }
        if (message.sender !== "") {
            writer.uint32(26).string(message.sender);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRegisterFeeCollectorRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.senderDeprecated = reader.bytes();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.feeCollector = reader.bytes();
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.sender = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.RegisterFeeCollectorRequest.$type,
            senderDeprecated: isSet(object.senderDeprecated)
                ? Buffer.from(bytesFromBase64(object.senderDeprecated))
                : Buffer.alloc(0),
            feeCollector: isSet(object.feeCollector)
                ? Buffer.from(bytesFromBase64(object.feeCollector))
                : Buffer.alloc(0),
            sender: isSet(object.sender) ? gt.String(object.sender) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.senderDeprecated.length !== 0) {
            obj.senderDeprecated = base64FromBytes(message.senderDeprecated);
        }
        if (message.feeCollector.length !== 0) {
            obj.feeCollector = base64FromBytes(message.feeCollector);
        }
        if (message.sender !== "") {
            obj.sender = message.sender;
        }
        return obj;
    },
    create(base) {
        return exports.RegisterFeeCollectorRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b, _c;
        const message = createBaseRegisterFeeCollectorRequest();
        message.senderDeprecated = (_a = object.senderDeprecated) !== null && _a !== void 0 ? _a : Buffer.alloc(0);
        message.feeCollector = (_b = object.feeCollector) !== null && _b !== void 0 ? _b : Buffer.alloc(0);
        message.sender = (_c = object.sender) !== null && _c !== void 0 ? _c : "";
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.RegisterFeeCollectorRequest.$type, exports.RegisterFeeCollectorRequest);
function createBaseRegisterFeeCollectorResponse() {
    return { $type: "axelar.axelarnet.v1beta1.RegisterFeeCollectorResponse" };
}
exports.RegisterFeeCollectorResponse = {
    $type: "axelar.axelarnet.v1beta1.RegisterFeeCollectorResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRegisterFeeCollectorResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.RegisterFeeCollectorResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.RegisterFeeCollectorResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseRegisterFeeCollectorResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.RegisterFeeCollectorResponse.$type, exports.RegisterFeeCollectorResponse);
function createBaseRetryIBCTransferRequest() {
    return {
        $type: "axelar.axelarnet.v1beta1.RetryIBCTransferRequest",
        senderDeprecated: Buffer.alloc(0),
        chain: "",
        id: long_1.default.UZERO,
        sender: "",
    };
}
exports.RetryIBCTransferRequest = {
    $type: "axelar.axelarnet.v1beta1.RetryIBCTransferRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.senderDeprecated.length !== 0) {
            writer.uint32(10).bytes(message.senderDeprecated);
        }
        if (message.chain !== "") {
            writer.uint32(18).string(message.chain);
        }
        if (!message.id.equals(long_1.default.UZERO)) {
            writer.uint32(24).uint64(message.id);
        }
        if (message.sender !== "") {
            writer.uint32(34).string(message.sender);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRetryIBCTransferRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.senderDeprecated = reader.bytes();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.chain = reader.string();
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.id = reader.uint64();
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.sender = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.RetryIBCTransferRequest.$type,
            senderDeprecated: isSet(object.senderDeprecated)
                ? Buffer.from(bytesFromBase64(object.senderDeprecated))
                : Buffer.alloc(0),
            chain: isSet(object.chain) ? gt.String(object.chain) : "",
            id: isSet(object.id) ? long_1.default.fromValue(object.id) : long_1.default.UZERO,
            sender: isSet(object.sender) ? gt.String(object.sender) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.senderDeprecated.length !== 0) {
            obj.senderDeprecated = base64FromBytes(message.senderDeprecated);
        }
        if (message.chain !== "") {
            obj.chain = message.chain;
        }
        if (!message.id.equals(long_1.default.UZERO)) {
            obj.id = (message.id || long_1.default.UZERO).toString();
        }
        if (message.sender !== "") {
            obj.sender = message.sender;
        }
        return obj;
    },
    create(base) {
        return exports.RetryIBCTransferRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b, _c;
        const message = createBaseRetryIBCTransferRequest();
        message.senderDeprecated = (_a = object.senderDeprecated) !== null && _a !== void 0 ? _a : Buffer.alloc(0);
        message.chain = (_b = object.chain) !== null && _b !== void 0 ? _b : "";
        message.id = object.id !== undefined && object.id !== null ? long_1.default.fromValue(object.id) : long_1.default.UZERO;
        message.sender = (_c = object.sender) !== null && _c !== void 0 ? _c : "";
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.RetryIBCTransferRequest.$type, exports.RetryIBCTransferRequest);
function createBaseRetryIBCTransferResponse() {
    return { $type: "axelar.axelarnet.v1beta1.RetryIBCTransferResponse" };
}
exports.RetryIBCTransferResponse = {
    $type: "axelar.axelarnet.v1beta1.RetryIBCTransferResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRetryIBCTransferResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.RetryIBCTransferResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.RetryIBCTransferResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseRetryIBCTransferResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.RetryIBCTransferResponse.$type, exports.RetryIBCTransferResponse);
function createBaseRouteMessageRequest() {
    return {
        $type: "axelar.axelarnet.v1beta1.RouteMessageRequest",
        senderDeprecated: Buffer.alloc(0),
        id: "",
        payload: Buffer.alloc(0),
        feegranter: Buffer.alloc(0),
        sender: "",
    };
}
exports.RouteMessageRequest = {
    $type: "axelar.axelarnet.v1beta1.RouteMessageRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.senderDeprecated.length !== 0) {
            writer.uint32(10).bytes(message.senderDeprecated);
        }
        if (message.id !== "") {
            writer.uint32(18).string(message.id);
        }
        if (message.payload.length !== 0) {
            writer.uint32(26).bytes(message.payload);
        }
        if (message.feegranter.length !== 0) {
            writer.uint32(34).bytes(message.feegranter);
        }
        if (message.sender !== "") {
            writer.uint32(42).string(message.sender);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRouteMessageRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.senderDeprecated = reader.bytes();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.id = reader.string();
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.payload = reader.bytes();
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.feegranter = reader.bytes();
                    continue;
                case 5:
                    if (tag !== 42) {
                        break;
                    }
                    message.sender = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.RouteMessageRequest.$type,
            senderDeprecated: isSet(object.senderDeprecated)
                ? Buffer.from(bytesFromBase64(object.senderDeprecated))
                : Buffer.alloc(0),
            id: isSet(object.id) ? gt.String(object.id) : "",
            payload: isSet(object.payload) ? Buffer.from(bytesFromBase64(object.payload)) : Buffer.alloc(0),
            feegranter: isSet(object.feegranter)
                ? Buffer.from(bytesFromBase64(object.feegranter))
                : Buffer.alloc(0),
            sender: isSet(object.sender) ? gt.String(object.sender) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.senderDeprecated.length !== 0) {
            obj.senderDeprecated = base64FromBytes(message.senderDeprecated);
        }
        if (message.id !== "") {
            obj.id = message.id;
        }
        if (message.payload.length !== 0) {
            obj.payload = base64FromBytes(message.payload);
        }
        if (message.feegranter.length !== 0) {
            obj.feegranter = base64FromBytes(message.feegranter);
        }
        if (message.sender !== "") {
            obj.sender = message.sender;
        }
        return obj;
    },
    create(base) {
        return exports.RouteMessageRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b, _c, _d, _e;
        const message = createBaseRouteMessageRequest();
        message.senderDeprecated = (_a = object.senderDeprecated) !== null && _a !== void 0 ? _a : Buffer.alloc(0);
        message.id = (_b = object.id) !== null && _b !== void 0 ? _b : "";
        message.payload = (_c = object.payload) !== null && _c !== void 0 ? _c : Buffer.alloc(0);
        message.feegranter = (_d = object.feegranter) !== null && _d !== void 0 ? _d : Buffer.alloc(0);
        message.sender = (_e = object.sender) !== null && _e !== void 0 ? _e : "";
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.RouteMessageRequest.$type, exports.RouteMessageRequest);
function createBaseRouteMessageResponse() {
    return { $type: "axelar.axelarnet.v1beta1.RouteMessageResponse" };
}
exports.RouteMessageResponse = {
    $type: "axelar.axelarnet.v1beta1.RouteMessageResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRouteMessageResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.RouteMessageResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.RouteMessageResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseRouteMessageResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.RouteMessageResponse.$type, exports.RouteMessageResponse);
function createBaseCallContractRequest() {
    return {
        $type: "axelar.axelarnet.v1beta1.CallContractRequest",
        senderDeprecated: Buffer.alloc(0),
        chain: "",
        contractAddress: "",
        payload: Buffer.alloc(0),
        fee: undefined,
        sender: "",
    };
}
exports.CallContractRequest = {
    $type: "axelar.axelarnet.v1beta1.CallContractRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.senderDeprecated.length !== 0) {
            writer.uint32(10).bytes(message.senderDeprecated);
        }
        if (message.chain !== "") {
            writer.uint32(18).string(message.chain);
        }
        if (message.contractAddress !== "") {
            writer.uint32(26).string(message.contractAddress);
        }
        if (message.payload.length !== 0) {
            writer.uint32(34).bytes(message.payload);
        }
        if (message.fee !== undefined) {
            types_2.Fee.encode(message.fee, writer.uint32(42).fork()).ldelim();
        }
        if (message.sender !== "") {
            writer.uint32(50).string(message.sender);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseCallContractRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.senderDeprecated = reader.bytes();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.chain = reader.string();
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.contractAddress = reader.string();
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.payload = reader.bytes();
                    continue;
                case 5:
                    if (tag !== 42) {
                        break;
                    }
                    message.fee = types_2.Fee.decode(reader, reader.uint32());
                    continue;
                case 6:
                    if (tag !== 50) {
                        break;
                    }
                    message.sender = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.CallContractRequest.$type,
            senderDeprecated: isSet(object.senderDeprecated)
                ? Buffer.from(bytesFromBase64(object.senderDeprecated))
                : Buffer.alloc(0),
            chain: isSet(object.chain) ? gt.String(object.chain) : "",
            contractAddress: isSet(object.contractAddress) ? gt.String(object.contractAddress) : "",
            payload: isSet(object.payload) ? Buffer.from(bytesFromBase64(object.payload)) : Buffer.alloc(0),
            fee: isSet(object.fee) ? types_2.Fee.fromJSON(object.fee) : undefined,
            sender: isSet(object.sender) ? gt.String(object.sender) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.senderDeprecated.length !== 0) {
            obj.senderDeprecated = base64FromBytes(message.senderDeprecated);
        }
        if (message.chain !== "") {
            obj.chain = message.chain;
        }
        if (message.contractAddress !== "") {
            obj.contractAddress = message.contractAddress;
        }
        if (message.payload.length !== 0) {
            obj.payload = base64FromBytes(message.payload);
        }
        if (message.fee !== undefined) {
            obj.fee = types_2.Fee.toJSON(message.fee);
        }
        if (message.sender !== "") {
            obj.sender = message.sender;
        }
        return obj;
    },
    create(base) {
        return exports.CallContractRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b, _c, _d, _e;
        const message = createBaseCallContractRequest();
        message.senderDeprecated = (_a = object.senderDeprecated) !== null && _a !== void 0 ? _a : Buffer.alloc(0);
        message.chain = (_b = object.chain) !== null && _b !== void 0 ? _b : "";
        message.contractAddress = (_c = object.contractAddress) !== null && _c !== void 0 ? _c : "";
        message.payload = (_d = object.payload) !== null && _d !== void 0 ? _d : Buffer.alloc(0);
        message.fee = object.fee !== undefined && object.fee !== null ? types_2.Fee.fromPartial(object.fee) : undefined;
        message.sender = (_e = object.sender) !== null && _e !== void 0 ? _e : "";
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.CallContractRequest.$type, exports.CallContractRequest);
function createBaseCallContractResponse() {
    return { $type: "axelar.axelarnet.v1beta1.CallContractResponse" };
}
exports.CallContractResponse = {
    $type: "axelar.axelarnet.v1beta1.CallContractResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseCallContractResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.CallContractResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.CallContractResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseCallContractResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.CallContractResponse.$type, exports.CallContractResponse);
function createBaseUpdateParamsRequest() {
    return { $type: "axelar.axelarnet.v1beta1.UpdateParamsRequest", authority: "", params: undefined };
}
exports.UpdateParamsRequest = {
    $type: "axelar.axelarnet.v1beta1.UpdateParamsRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.authority !== "") {
            writer.uint32(10).string(message.authority);
        }
        if (message.params !== undefined) {
            params_1.Params.encode(message.params, writer.uint32(18).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseUpdateParamsRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.authority = reader.string();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.params = params_1.Params.decode(reader, reader.uint32());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.UpdateParamsRequest.$type,
            authority: isSet(object.authority) ? gt.String(object.authority) : "",
            params: isSet(object.params) ? params_1.Params.fromJSON(object.params) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.authority !== "") {
            obj.authority = message.authority;
        }
        if (message.params !== undefined) {
            obj.params = params_1.Params.toJSON(message.params);
        }
        return obj;
    },
    create(base) {
        return exports.UpdateParamsRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a;
        const message = createBaseUpdateParamsRequest();
        message.authority = (_a = object.authority) !== null && _a !== void 0 ? _a : "";
        message.params =
            object.params !== undefined && object.params !== null ? params_1.Params.fromPartial(object.params) : undefined;
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.UpdateParamsRequest.$type, exports.UpdateParamsRequest);
function createBaseUpdateParamsResponse() {
    return { $type: "axelar.axelarnet.v1beta1.UpdateParamsResponse" };
}
exports.UpdateParamsResponse = {
    $type: "axelar.axelarnet.v1beta1.UpdateParamsResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseUpdateParamsResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.UpdateParamsResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.UpdateParamsResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseUpdateParamsResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.UpdateParamsResponse.$type, exports.UpdateParamsResponse);
const gt = (() => {
    if (typeof globalThis !== "undefined") {
        return globalThis;
    }
    if (typeof self !== "undefined") {
        return self;
    }
    if (typeof window !== "undefined") {
        return window;
    }
    if (typeof global !== "undefined") {
        return global;
    }
    throw "Unable to locate global object";
})();
function bytesFromBase64(b64) {
    return Uint8Array.from(gt.Buffer.from(b64, "base64"));
}
function base64FromBytes(arr) {
    return gt.Buffer.from(arr).toString("base64");
}
if (minimal_1.default.util.Long !== long_1.default) {
    minimal_1.default.util.Long = long_1.default;
    minimal_1.default.configure();
}
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=tx.js.map