import Long from "long";
import _m0 from "protobufjs/minimal";
import { Coin } from "../../../../cosmos/base/v1beta1/coin";
import { KeyType } from "../../../tss/exported/v1beta1/types";
export declare const protobufPackage = "axelar.nexus.exported.v1beta1";
export declare enum TransferState {
    TRANSFER_STATE_UNSPECIFIED = 0,
    TRANSFER_STATE_PENDING = 1,
    TRANSFER_STATE_ARCHIVED = 2,
    TRANSFER_STATE_INSUFFICIENT_AMOUNT = 3,
    TRANSFER_STATE_FAILED = 4,
    UNRECOGNIZED = -1
}
export declare function transferStateFromJSON(object: any): TransferState;
export declare function transferStateToJSON(object: TransferState): string;
export declare enum TransferDirection {
    TRANSFER_DIRECTION_UNSPECIFIED = 0,
    TRANSFER_DIRECTION_FROM = 1,
    TRANSFER_DIRECTION_TO = 2,
    UNRECOGNIZED = -1
}
export declare function transferDirectionFromJSON(object: any): TransferDirection;
export declare function transferDirectionToJSON(object: TransferDirection): string;
/** Chain represents the properties of a registered blockchain */
export interface Chain {
    $type: "axelar.nexus.exported.v1beta1.Chain";
    name: string;
    /**
     * DEPRECATED: Removed in v0.14, reinstated in v1.3 for backward
     * compatibility. This field must remain to allow decoding of historical
     * transactions. DO NOT use in new code.
     *
     * @deprecated
     */
    nativeAssetDeprecated: string;
    supportsForeignAssets: boolean;
    keyType: KeyType;
    module: string;
}
/** CrossChainAddress represents a generalized address on any registered chain */
export interface CrossChainAddress {
    $type: "axelar.nexus.exported.v1beta1.CrossChainAddress";
    chain?: Chain | undefined;
    address: string;
}
/**
 * CrossChainTransfer represents a generalized transfer of some asset to a
 * registered blockchain
 */
export interface CrossChainTransfer {
    $type: "axelar.nexus.exported.v1beta1.CrossChainTransfer";
    recipient?: CrossChainAddress | undefined;
    asset?: Coin | undefined;
    id: Long;
    state: TransferState;
}
/** TransferFee represents accumulated fees generated by the network */
export interface TransferFee {
    $type: "axelar.nexus.exported.v1beta1.TransferFee";
    coins: Coin[];
}
export interface FeeInfo {
    $type: "axelar.nexus.exported.v1beta1.FeeInfo";
    chain: string;
    asset: string;
    feeRate: Buffer;
    minFee: Buffer;
    maxFee: Buffer;
}
export interface Asset {
    $type: "axelar.nexus.exported.v1beta1.Asset";
    denom: string;
    /**
     * DEPRECATED: Removed in v0.15, reinstated in v1.3 for backward
     * compatibility. This field must remain to allow decoding of historical
     * transactions. DO NOT use in new code.
     *
     * @deprecated
     */
    minAmountDeprecated: Buffer;
    isNativeAsset: boolean;
}
export interface GeneralMessage {
    $type: "axelar.nexus.exported.v1beta1.GeneralMessage";
    id: string;
    sender?: CrossChainAddress | undefined;
    recipient?: CrossChainAddress | undefined;
    payloadHash: Buffer;
    status: GeneralMessage_Status;
    asset?: Coin | undefined;
    sourceTxId: Buffer;
    sourceTxIndex: Long;
}
export declare enum GeneralMessage_Status {
    STATUS_UNSPECIFIED = 0,
    STATUS_APPROVED = 1,
    STATUS_PROCESSING = 2,
    STATUS_EXECUTED = 3,
    STATUS_FAILED = 4,
    UNRECOGNIZED = -1
}
export declare function generalMessage_StatusFromJSON(object: any): GeneralMessage_Status;
export declare function generalMessage_StatusToJSON(object: GeneralMessage_Status): string;
export interface WasmMessage {
    $type: "axelar.nexus.exported.v1beta1.WasmMessage";
    sourceChain: string;
    sourceAddress: string;
    destinationChain: string;
    destinationAddress: string;
    payloadHash: Buffer;
    sourceTxId: Buffer;
    sourceTxIndex: Long;
    sender: Buffer;
    id: string;
}
export declare const Chain: {
    $type: "axelar.nexus.exported.v1beta1.Chain";
    encode(message: Chain, writer?: _m0.Writer): _m0.Writer;
    decode(input: _m0.Reader | Uint8Array, length?: number): Chain;
    fromJSON(object: any): Chain;
    toJSON(message: Chain): unknown;
    create<I extends Exact<DeepPartial<Chain>, I>>(base?: I): Chain;
    fromPartial<I extends Exact<DeepPartial<Chain>, I>>(object: I): Chain;
};
export declare const CrossChainAddress: {
    $type: "axelar.nexus.exported.v1beta1.CrossChainAddress";
    encode(message: CrossChainAddress, writer?: _m0.Writer): _m0.Writer;
    decode(input: _m0.Reader | Uint8Array, length?: number): CrossChainAddress;
    fromJSON(object: any): CrossChainAddress;
    toJSON(message: CrossChainAddress): unknown;
    create<I extends Exact<DeepPartial<CrossChainAddress>, I>>(base?: I): CrossChainAddress;
    fromPartial<I extends Exact<DeepPartial<CrossChainAddress>, I>>(object: I): CrossChainAddress;
};
export declare const CrossChainTransfer: {
    $type: "axelar.nexus.exported.v1beta1.CrossChainTransfer";
    encode(message: CrossChainTransfer, writer?: _m0.Writer): _m0.Writer;
    decode(input: _m0.Reader | Uint8Array, length?: number): CrossChainTransfer;
    fromJSON(object: any): CrossChainTransfer;
    toJSON(message: CrossChainTransfer): unknown;
    create<I extends Exact<DeepPartial<CrossChainTransfer>, I>>(base?: I): CrossChainTransfer;
    fromPartial<I extends Exact<DeepPartial<CrossChainTransfer>, I>>(object: I): CrossChainTransfer;
};
export declare const TransferFee: {
    $type: "axelar.nexus.exported.v1beta1.TransferFee";
    encode(message: TransferFee, writer?: _m0.Writer): _m0.Writer;
    decode(input: _m0.Reader | Uint8Array, length?: number): TransferFee;
    fromJSON(object: any): TransferFee;
    toJSON(message: TransferFee): unknown;
    create<I extends Exact<DeepPartial<TransferFee>, I>>(base?: I): TransferFee;
    fromPartial<I extends Exact<DeepPartial<TransferFee>, I>>(object: I): TransferFee;
};
export declare const FeeInfo: {
    $type: "axelar.nexus.exported.v1beta1.FeeInfo";
    encode(message: FeeInfo, writer?: _m0.Writer): _m0.Writer;
    decode(input: _m0.Reader | Uint8Array, length?: number): FeeInfo;
    fromJSON(object: any): FeeInfo;
    toJSON(message: FeeInfo): unknown;
    create<I extends Exact<DeepPartial<FeeInfo>, I>>(base?: I): FeeInfo;
    fromPartial<I extends Exact<DeepPartial<FeeInfo>, I>>(object: I): FeeInfo;
};
export declare const Asset: {
    $type: "axelar.nexus.exported.v1beta1.Asset";
    encode(message: Asset, writer?: _m0.Writer): _m0.Writer;
    decode(input: _m0.Reader | Uint8Array, length?: number): Asset;
    fromJSON(object: any): Asset;
    toJSON(message: Asset): unknown;
    create<I extends Exact<DeepPartial<Asset>, I>>(base?: I): Asset;
    fromPartial<I extends Exact<DeepPartial<Asset>, I>>(object: I): Asset;
};
export declare const GeneralMessage: {
    $type: "axelar.nexus.exported.v1beta1.GeneralMessage";
    encode(message: GeneralMessage, writer?: _m0.Writer): _m0.Writer;
    decode(input: _m0.Reader | Uint8Array, length?: number): GeneralMessage;
    fromJSON(object: any): GeneralMessage;
    toJSON(message: GeneralMessage): unknown;
    create<I extends Exact<DeepPartial<GeneralMessage>, I>>(base?: I): GeneralMessage;
    fromPartial<I extends Exact<DeepPartial<GeneralMessage>, I>>(object: I): GeneralMessage;
};
export declare const WasmMessage: {
    $type: "axelar.nexus.exported.v1beta1.WasmMessage";
    encode(message: WasmMessage, writer?: _m0.Writer): _m0.Writer;
    decode(input: _m0.Reader | Uint8Array, length?: number): WasmMessage;
    fromJSON(object: any): WasmMessage;
    toJSON(message: WasmMessage): unknown;
    create<I extends Exact<DeepPartial<WasmMessage>, I>>(base?: I): WasmMessage;
    fromPartial<I extends Exact<DeepPartial<WasmMessage>, I>>(object: I): WasmMessage;
};
type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;
export type DeepPartial<T> = T extends Builtin ? T : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>> : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>> : T extends {} ? {
    [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]>;
} : Partial<T>;
type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P : P & {
    [K in keyof P]: Exact<P[K], I[K]>;
} & {
    [K in Exclude<keyof I, KeysOfUnion<P> | "$type">]: never;
};
export {};
