// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.21.12
// source: axelar/snapshot/v1beta1/tx.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { messageTypeRegistry } from "../../../typeRegistry";
import { Params } from "./params";

export const protobufPackage = "axelar.snapshot.v1beta1";

export interface RegisterProxyRequest {
  $type: "axelar.snapshot.v1beta1.RegisterProxyRequest";
  proxyAddr: Buffer;
  sender: string;
}

export interface RegisterProxyResponse {
  $type: "axelar.snapshot.v1beta1.RegisterProxyResponse";
}

export interface DeactivateProxyRequest {
  $type: "axelar.snapshot.v1beta1.DeactivateProxyRequest";
  /** @deprecated */
  senderBz: Buffer;
  sender: string;
}

export interface DeactivateProxyResponse {
  $type: "axelar.snapshot.v1beta1.DeactivateProxyResponse";
}

export interface UpdateParamsRequest {
  $type: "axelar.snapshot.v1beta1.UpdateParamsRequest";
  authority: string;
  params?: Params | undefined;
}

export interface UpdateParamsResponse {
  $type: "axelar.snapshot.v1beta1.UpdateParamsResponse";
}

function createBaseRegisterProxyRequest(): RegisterProxyRequest {
  return { $type: "axelar.snapshot.v1beta1.RegisterProxyRequest", proxyAddr: Buffer.alloc(0), sender: "" };
}

export const RegisterProxyRequest = {
  $type: "axelar.snapshot.v1beta1.RegisterProxyRequest" as const,

  encode(message: RegisterProxyRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.proxyAddr.length !== 0) {
      writer.uint32(18).bytes(message.proxyAddr);
    }
    if (message.sender !== "") {
      writer.uint32(26).string(message.sender);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RegisterProxyRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterProxyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2:
          if (tag !== 18) {
            break;
          }

          message.proxyAddr = reader.bytes() as Buffer;
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.sender = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterProxyRequest {
    return {
      $type: RegisterProxyRequest.$type,
      proxyAddr: isSet(object.proxyAddr) ? Buffer.from(bytesFromBase64(object.proxyAddr)) : Buffer.alloc(0),
      sender: isSet(object.sender) ? gt.String(object.sender) : "",
    };
  },

  toJSON(message: RegisterProxyRequest): unknown {
    const obj: any = {};
    if (message.proxyAddr.length !== 0) {
      obj.proxyAddr = base64FromBytes(message.proxyAddr);
    }
    if (message.sender !== "") {
      obj.sender = message.sender;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RegisterProxyRequest>, I>>(base?: I): RegisterProxyRequest {
    return RegisterProxyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegisterProxyRequest>, I>>(object: I): RegisterProxyRequest {
    const message = createBaseRegisterProxyRequest();
    message.proxyAddr = object.proxyAddr ?? Buffer.alloc(0);
    message.sender = object.sender ?? "";
    return message;
  },
};

messageTypeRegistry.set(RegisterProxyRequest.$type, RegisterProxyRequest);

function createBaseRegisterProxyResponse(): RegisterProxyResponse {
  return { $type: "axelar.snapshot.v1beta1.RegisterProxyResponse" };
}

export const RegisterProxyResponse = {
  $type: "axelar.snapshot.v1beta1.RegisterProxyResponse" as const,

  encode(_: RegisterProxyResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RegisterProxyResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterProxyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): RegisterProxyResponse {
    return { $type: RegisterProxyResponse.$type };
  },

  toJSON(_: RegisterProxyResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<RegisterProxyResponse>, I>>(base?: I): RegisterProxyResponse {
    return RegisterProxyResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegisterProxyResponse>, I>>(_: I): RegisterProxyResponse {
    const message = createBaseRegisterProxyResponse();
    return message;
  },
};

messageTypeRegistry.set(RegisterProxyResponse.$type, RegisterProxyResponse);

function createBaseDeactivateProxyRequest(): DeactivateProxyRequest {
  return { $type: "axelar.snapshot.v1beta1.DeactivateProxyRequest", senderBz: Buffer.alloc(0), sender: "" };
}

export const DeactivateProxyRequest = {
  $type: "axelar.snapshot.v1beta1.DeactivateProxyRequest" as const,

  encode(message: DeactivateProxyRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.senderBz.length !== 0) {
      writer.uint32(10).bytes(message.senderBz);
    }
    if (message.sender !== "") {
      writer.uint32(18).string(message.sender);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DeactivateProxyRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeactivateProxyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.senderBz = reader.bytes() as Buffer;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.sender = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeactivateProxyRequest {
    return {
      $type: DeactivateProxyRequest.$type,
      senderBz: isSet(object.senderBz) ? Buffer.from(bytesFromBase64(object.senderBz)) : Buffer.alloc(0),
      sender: isSet(object.sender) ? gt.String(object.sender) : "",
    };
  },

  toJSON(message: DeactivateProxyRequest): unknown {
    const obj: any = {};
    if (message.senderBz.length !== 0) {
      obj.senderBz = base64FromBytes(message.senderBz);
    }
    if (message.sender !== "") {
      obj.sender = message.sender;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeactivateProxyRequest>, I>>(base?: I): DeactivateProxyRequest {
    return DeactivateProxyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeactivateProxyRequest>, I>>(object: I): DeactivateProxyRequest {
    const message = createBaseDeactivateProxyRequest();
    message.senderBz = object.senderBz ?? Buffer.alloc(0);
    message.sender = object.sender ?? "";
    return message;
  },
};

messageTypeRegistry.set(DeactivateProxyRequest.$type, DeactivateProxyRequest);

function createBaseDeactivateProxyResponse(): DeactivateProxyResponse {
  return { $type: "axelar.snapshot.v1beta1.DeactivateProxyResponse" };
}

export const DeactivateProxyResponse = {
  $type: "axelar.snapshot.v1beta1.DeactivateProxyResponse" as const,

  encode(_: DeactivateProxyResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DeactivateProxyResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeactivateProxyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): DeactivateProxyResponse {
    return { $type: DeactivateProxyResponse.$type };
  },

  toJSON(_: DeactivateProxyResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<DeactivateProxyResponse>, I>>(base?: I): DeactivateProxyResponse {
    return DeactivateProxyResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeactivateProxyResponse>, I>>(_: I): DeactivateProxyResponse {
    const message = createBaseDeactivateProxyResponse();
    return message;
  },
};

messageTypeRegistry.set(DeactivateProxyResponse.$type, DeactivateProxyResponse);

function createBaseUpdateParamsRequest(): UpdateParamsRequest {
  return { $type: "axelar.snapshot.v1beta1.UpdateParamsRequest", authority: "", params: undefined };
}

export const UpdateParamsRequest = {
  $type: "axelar.snapshot.v1beta1.UpdateParamsRequest" as const,

  encode(message: UpdateParamsRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): UpdateParamsRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateParamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateParamsRequest {
    return {
      $type: UpdateParamsRequest.$type,
      authority: isSet(object.authority) ? gt.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: UpdateParamsRequest): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateParamsRequest>, I>>(base?: I): UpdateParamsRequest {
    return UpdateParamsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateParamsRequest>, I>>(object: I): UpdateParamsRequest {
    const message = createBaseUpdateParamsRequest();
    message.authority = object.authority ?? "";
    message.params =
      object.params !== undefined && object.params !== null ? Params.fromPartial(object.params) : undefined;
    return message;
  },
};

messageTypeRegistry.set(UpdateParamsRequest.$type, UpdateParamsRequest);

function createBaseUpdateParamsResponse(): UpdateParamsResponse {
  return { $type: "axelar.snapshot.v1beta1.UpdateParamsResponse" };
}

export const UpdateParamsResponse = {
  $type: "axelar.snapshot.v1beta1.UpdateParamsResponse" as const,

  encode(_: UpdateParamsResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): UpdateParamsResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): UpdateParamsResponse {
    return { $type: UpdateParamsResponse.$type };
  },

  toJSON(_: UpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateParamsResponse>, I>>(base?: I): UpdateParamsResponse {
    return UpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateParamsResponse>, I>>(_: I): UpdateParamsResponse {
    const message = createBaseUpdateParamsResponse();
    return message;
  },
};

messageTypeRegistry.set(UpdateParamsResponse.$type, UpdateParamsResponse);

declare const self: any | undefined;
declare const window: any | undefined;
declare const global: any | undefined;
const gt: any = (() => {
  if (typeof globalThis !== "undefined") {
    return globalThis;
  }
  if (typeof self !== "undefined") {
    return self;
  }
  if (typeof window !== "undefined") {
    return window;
  }
  if (typeof global !== "undefined") {
    return global;
  }
  throw "Unable to locate global object";
})();

function bytesFromBase64(b64: string): Uint8Array {
  return Uint8Array.from(gt.Buffer.from(b64, "base64"));
}

function base64FromBytes(arr: Uint8Array): string {
  return gt.Buffer.from(arr).toString("base64");
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends Long
  ? string | number | Long
  : T extends globalThis.Array<infer U>
  ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U>
  ? ReadonlyArray<DeepPartial<U>>
  : T extends {}
  ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P> | "$type">]: never };

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
