// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.33.4
// source: axelar/snapshot/v1beta1/types.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { messageTypeRegistry } from "../../../typeRegistry";

export const protobufPackage = "axelar.snapshot.v1beta1";

export interface ProxiedValidator {
  $type: "axelar.snapshot.v1beta1.ProxiedValidator";
  validator: Buffer;
  proxy: Buffer;
  active: boolean;
}

function createBaseProxiedValidator(): ProxiedValidator {
  return {
    $type: "axelar.snapshot.v1beta1.ProxiedValidator",
    validator: Buffer.alloc(0),
    proxy: Buffer.alloc(0),
    active: false,
  };
}

export const ProxiedValidator = {
  $type: "axelar.snapshot.v1beta1.ProxiedValidator" as const,

  encode(message: ProxiedValidator, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.validator.length !== 0) {
      writer.uint32(10).bytes(message.validator);
    }
    if (message.proxy.length !== 0) {
      writer.uint32(18).bytes(message.proxy);
    }
    if (message.active !== false) {
      writer.uint32(24).bool(message.active);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ProxiedValidator {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProxiedValidator();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.validator = reader.bytes() as Buffer;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.proxy = reader.bytes() as Buffer;
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.active = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProxiedValidator {
    return {
      $type: ProxiedValidator.$type,
      validator: isSet(object.validator) ? Buffer.from(bytesFromBase64(object.validator)) : Buffer.alloc(0),
      proxy: isSet(object.proxy) ? Buffer.from(bytesFromBase64(object.proxy)) : Buffer.alloc(0),
      active: isSet(object.active) ? gt.Boolean(object.active) : false,
    };
  },

  toJSON(message: ProxiedValidator): unknown {
    const obj: any = {};
    if (message.validator.length !== 0) {
      obj.validator = base64FromBytes(message.validator);
    }
    if (message.proxy.length !== 0) {
      obj.proxy = base64FromBytes(message.proxy);
    }
    if (message.active !== false) {
      obj.active = message.active;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProxiedValidator>, I>>(base?: I): ProxiedValidator {
    return ProxiedValidator.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProxiedValidator>, I>>(object: I): ProxiedValidator {
    const message = createBaseProxiedValidator();
    message.validator = object.validator ?? Buffer.alloc(0);
    message.proxy = object.proxy ?? Buffer.alloc(0);
    message.active = object.active ?? false;
    return message;
  },
};

messageTypeRegistry.set(ProxiedValidator.$type, ProxiedValidator);

declare const self: any | undefined;
declare const window: any | undefined;
declare const global: any | undefined;
const gt: any = (() => {
  if (typeof globalThis !== "undefined") {
    return globalThis;
  }
  if (typeof self !== "undefined") {
    return self;
  }
  if (typeof window !== "undefined") {
    return window;
  }
  if (typeof global !== "undefined") {
    return global;
  }
  throw "Unable to locate global object";
})();

function bytesFromBase64(b64: string): Uint8Array {
  return Uint8Array.from(gt.Buffer.from(b64, "base64"));
}

function base64FromBytes(arr: Uint8Array): string {
  return gt.Buffer.from(arr).toString("base64");
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends Long
  ? string | number | Long
  : T extends globalThis.Array<infer U>
  ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U>
  ? ReadonlyArray<DeepPartial<U>>
  : T extends {}
  ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P> | "$type">]: never };

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
