"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.31.1
// source: axelar/tss/v1beta1/types.proto
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ValidatorStatus = exports.ExternalKeys = exports.KeyRecoveryInfo_PrivateEntry = exports.KeyRecoveryInfo = exports.MultisigInfo_Info = exports.MultisigInfo = exports.KeyInfo = exports.KeygenVoteData = exports.protobufPackage = void 0;
/* eslint-disable */
const long_1 = __importDefault(require("long"));
const minimal_1 = __importDefault(require("protobufjs/minimal"));
const typeRegistry_1 = require("../../../typeRegistry");
const types_1 = require("../exported/v1beta1/types");
exports.protobufPackage = "axelar.tss.v1beta1";
function createBaseKeygenVoteData() {
    return {
        $type: "axelar.tss.v1beta1.KeygenVoteData",
        pubKey: Buffer.alloc(0),
        groupRecoveryInfo: Buffer.alloc(0),
    };
}
exports.KeygenVoteData = {
    $type: "axelar.tss.v1beta1.KeygenVoteData",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.pubKey.length !== 0) {
            writer.uint32(10).bytes(message.pubKey);
        }
        if (message.groupRecoveryInfo.length !== 0) {
            writer.uint32(18).bytes(message.groupRecoveryInfo);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseKeygenVoteData();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.pubKey = reader.bytes();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.groupRecoveryInfo = reader.bytes();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.KeygenVoteData.$type,
            pubKey: isSet(object.pubKey) ? Buffer.from(bytesFromBase64(object.pubKey)) : Buffer.alloc(0),
            groupRecoveryInfo: isSet(object.groupRecoveryInfo)
                ? Buffer.from(bytesFromBase64(object.groupRecoveryInfo))
                : Buffer.alloc(0),
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.pubKey.length !== 0) {
            obj.pubKey = base64FromBytes(message.pubKey);
        }
        if (message.groupRecoveryInfo.length !== 0) {
            obj.groupRecoveryInfo = base64FromBytes(message.groupRecoveryInfo);
        }
        return obj;
    },
    create(base) {
        return exports.KeygenVoteData.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b;
        const message = createBaseKeygenVoteData();
        message.pubKey = (_a = object.pubKey) !== null && _a !== void 0 ? _a : Buffer.alloc(0);
        message.groupRecoveryInfo = (_b = object.groupRecoveryInfo) !== null && _b !== void 0 ? _b : Buffer.alloc(0);
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.KeygenVoteData.$type, exports.KeygenVoteData);
function createBaseKeyInfo() {
    return { $type: "axelar.tss.v1beta1.KeyInfo", keyId: "", keyRole: 0, keyType: 0 };
}
exports.KeyInfo = {
    $type: "axelar.tss.v1beta1.KeyInfo",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.keyId !== "") {
            writer.uint32(10).string(message.keyId);
        }
        if (message.keyRole !== 0) {
            writer.uint32(16).int32(message.keyRole);
        }
        if (message.keyType !== 0) {
            writer.uint32(24).int32(message.keyType);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseKeyInfo();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.keyId = reader.string();
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.keyRole = reader.int32();
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.keyType = reader.int32();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.KeyInfo.$type,
            keyId: isSet(object.keyId) ? gt.String(object.keyId) : "",
            keyRole: isSet(object.keyRole) ? (0, types_1.keyRoleFromJSON)(object.keyRole) : 0,
            keyType: isSet(object.keyType) ? (0, types_1.keyTypeFromJSON)(object.keyType) : 0,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.keyId !== "") {
            obj.keyId = message.keyId;
        }
        if (message.keyRole !== 0) {
            obj.keyRole = (0, types_1.keyRoleToJSON)(message.keyRole);
        }
        if (message.keyType !== 0) {
            obj.keyType = (0, types_1.keyTypeToJSON)(message.keyType);
        }
        return obj;
    },
    create(base) {
        return exports.KeyInfo.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b, _c;
        const message = createBaseKeyInfo();
        message.keyId = (_a = object.keyId) !== null && _a !== void 0 ? _a : "";
        message.keyRole = (_b = object.keyRole) !== null && _b !== void 0 ? _b : 0;
        message.keyType = (_c = object.keyType) !== null && _c !== void 0 ? _c : 0;
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.KeyInfo.$type, exports.KeyInfo);
function createBaseMultisigInfo() {
    return {
        $type: "axelar.tss.v1beta1.MultisigInfo",
        id: "",
        timeout: long_1.default.ZERO,
        targetNum: long_1.default.ZERO,
        infos: [],
    };
}
exports.MultisigInfo = {
    $type: "axelar.tss.v1beta1.MultisigInfo",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.id !== "") {
            writer.uint32(10).string(message.id);
        }
        if (!message.timeout.equals(long_1.default.ZERO)) {
            writer.uint32(16).int64(message.timeout);
        }
        if (!message.targetNum.equals(long_1.default.ZERO)) {
            writer.uint32(24).int64(message.targetNum);
        }
        for (const v of message.infos) {
            exports.MultisigInfo_Info.encode(v, writer.uint32(34).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseMultisigInfo();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.id = reader.string();
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.timeout = reader.int64();
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.targetNum = reader.int64();
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.infos.push(exports.MultisigInfo_Info.decode(reader, reader.uint32()));
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.MultisigInfo.$type,
            id: isSet(object.id) ? gt.String(object.id) : "",
            timeout: isSet(object.timeout) ? long_1.default.fromValue(object.timeout) : long_1.default.ZERO,
            targetNum: isSet(object.targetNum) ? long_1.default.fromValue(object.targetNum) : long_1.default.ZERO,
            infos: gt.Array.isArray(object === null || object === void 0 ? void 0 : object.infos)
                ? object.infos.map((e) => exports.MultisigInfo_Info.fromJSON(e))
                : [],
        };
    },
    toJSON(message) {
        var _a;
        const obj = {};
        if (message.id !== "") {
            obj.id = message.id;
        }
        if (!message.timeout.equals(long_1.default.ZERO)) {
            obj.timeout = (message.timeout || long_1.default.ZERO).toString();
        }
        if (!message.targetNum.equals(long_1.default.ZERO)) {
            obj.targetNum = (message.targetNum || long_1.default.ZERO).toString();
        }
        if ((_a = message.infos) === null || _a === void 0 ? void 0 : _a.length) {
            obj.infos = message.infos.map((e) => exports.MultisigInfo_Info.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return exports.MultisigInfo.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b;
        const message = createBaseMultisigInfo();
        message.id = (_a = object.id) !== null && _a !== void 0 ? _a : "";
        message.timeout =
            object.timeout !== undefined && object.timeout !== null ? long_1.default.fromValue(object.timeout) : long_1.default.ZERO;
        message.targetNum =
            object.targetNum !== undefined && object.targetNum !== null
                ? long_1.default.fromValue(object.targetNum)
                : long_1.default.ZERO;
        message.infos = ((_b = object.infos) === null || _b === void 0 ? void 0 : _b.map((e) => exports.MultisigInfo_Info.fromPartial(e))) || [];
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.MultisigInfo.$type, exports.MultisigInfo);
function createBaseMultisigInfo_Info() {
    return { $type: "axelar.tss.v1beta1.MultisigInfo.Info", participant: Buffer.alloc(0), data: [] };
}
exports.MultisigInfo_Info = {
    $type: "axelar.tss.v1beta1.MultisigInfo.Info",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.participant.length !== 0) {
            writer.uint32(10).bytes(message.participant);
        }
        for (const v of message.data) {
            writer.uint32(18).bytes(v);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseMultisigInfo_Info();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.participant = reader.bytes();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.data.push(reader.bytes());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.MultisigInfo_Info.$type,
            participant: isSet(object.participant)
                ? Buffer.from(bytesFromBase64(object.participant))
                : Buffer.alloc(0),
            data: gt.Array.isArray(object === null || object === void 0 ? void 0 : object.data)
                ? object.data.map((e) => Buffer.from(bytesFromBase64(e)))
                : [],
        };
    },
    toJSON(message) {
        var _a;
        const obj = {};
        if (message.participant.length !== 0) {
            obj.participant = base64FromBytes(message.participant);
        }
        if ((_a = message.data) === null || _a === void 0 ? void 0 : _a.length) {
            obj.data = message.data.map((e) => base64FromBytes(e));
        }
        return obj;
    },
    create(base) {
        return exports.MultisigInfo_Info.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b;
        const message = createBaseMultisigInfo_Info();
        message.participant = (_a = object.participant) !== null && _a !== void 0 ? _a : Buffer.alloc(0);
        message.data = ((_b = object.data) === null || _b === void 0 ? void 0 : _b.map((e) => e)) || [];
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.MultisigInfo_Info.$type, exports.MultisigInfo_Info);
function createBaseKeyRecoveryInfo() {
    return { $type: "axelar.tss.v1beta1.KeyRecoveryInfo", keyId: "", public: Buffer.alloc(0), private: {} };
}
exports.KeyRecoveryInfo = {
    $type: "axelar.tss.v1beta1.KeyRecoveryInfo",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.keyId !== "") {
            writer.uint32(10).string(message.keyId);
        }
        if (message.public.length !== 0) {
            writer.uint32(18).bytes(message.public);
        }
        Object.entries(message.private).forEach(([key, value]) => {
            exports.KeyRecoveryInfo_PrivateEntry.encode({
                $type: "axelar.tss.v1beta1.KeyRecoveryInfo.PrivateEntry",
                key: key,
                value,
            }, writer.uint32(26).fork()).ldelim();
        });
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseKeyRecoveryInfo();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.keyId = reader.string();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.public = reader.bytes();
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    const entry3 = exports.KeyRecoveryInfo_PrivateEntry.decode(reader, reader.uint32());
                    if (entry3.value !== undefined) {
                        message.private[entry3.key] = entry3.value;
                    }
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.KeyRecoveryInfo.$type,
            keyId: isSet(object.keyId) ? gt.String(object.keyId) : "",
            public: isSet(object.public) ? Buffer.from(bytesFromBase64(object.public)) : Buffer.alloc(0),
            private: isObject(object.private)
                ? Object.entries(object.private).reduce((acc, [key, value]) => {
                    acc[key] = Buffer.from(bytesFromBase64(value));
                    return acc;
                }, {})
                : {},
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.keyId !== "") {
            obj.keyId = message.keyId;
        }
        if (message.public.length !== 0) {
            obj.public = base64FromBytes(message.public);
        }
        if (message.private) {
            const entries = Object.entries(message.private);
            if (entries.length > 0) {
                obj.private = {};
                entries.forEach(([k, v]) => {
                    obj.private[k] = base64FromBytes(v);
                });
            }
        }
        return obj;
    },
    create(base) {
        return exports.KeyRecoveryInfo.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b, _c;
        const message = createBaseKeyRecoveryInfo();
        message.keyId = (_a = object.keyId) !== null && _a !== void 0 ? _a : "";
        message.public = (_b = object.public) !== null && _b !== void 0 ? _b : Buffer.alloc(0);
        message.private = Object.entries((_c = object.private) !== null && _c !== void 0 ? _c : {}).reduce((acc, [key, value]) => {
            if (value !== undefined) {
                acc[key] = value;
            }
            return acc;
        }, {});
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.KeyRecoveryInfo.$type, exports.KeyRecoveryInfo);
function createBaseKeyRecoveryInfo_PrivateEntry() {
    return { $type: "axelar.tss.v1beta1.KeyRecoveryInfo.PrivateEntry", key: "", value: Buffer.alloc(0) };
}
exports.KeyRecoveryInfo_PrivateEntry = {
    $type: "axelar.tss.v1beta1.KeyRecoveryInfo.PrivateEntry",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.key !== "") {
            writer.uint32(10).string(message.key);
        }
        if (message.value.length !== 0) {
            writer.uint32(18).bytes(message.value);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseKeyRecoveryInfo_PrivateEntry();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.key = reader.string();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.value = reader.bytes();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.KeyRecoveryInfo_PrivateEntry.$type,
            key: isSet(object.key) ? gt.String(object.key) : "",
            value: isSet(object.value) ? Buffer.from(bytesFromBase64(object.value)) : Buffer.alloc(0),
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.key !== "") {
            obj.key = message.key;
        }
        if (message.value.length !== 0) {
            obj.value = base64FromBytes(message.value);
        }
        return obj;
    },
    create(base) {
        return exports.KeyRecoveryInfo_PrivateEntry.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b;
        const message = createBaseKeyRecoveryInfo_PrivateEntry();
        message.key = (_a = object.key) !== null && _a !== void 0 ? _a : "";
        message.value = (_b = object.value) !== null && _b !== void 0 ? _b : Buffer.alloc(0);
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.KeyRecoveryInfo_PrivateEntry.$type, exports.KeyRecoveryInfo_PrivateEntry);
function createBaseExternalKeys() {
    return { $type: "axelar.tss.v1beta1.ExternalKeys", chain: "", keyIds: [] };
}
exports.ExternalKeys = {
    $type: "axelar.tss.v1beta1.ExternalKeys",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.chain !== "") {
            writer.uint32(10).string(message.chain);
        }
        for (const v of message.keyIds) {
            writer.uint32(18).string(v);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseExternalKeys();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.chain = reader.string();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.keyIds.push(reader.string());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.ExternalKeys.$type,
            chain: isSet(object.chain) ? gt.String(object.chain) : "",
            keyIds: gt.Array.isArray(object === null || object === void 0 ? void 0 : object.keyIds) ? object.keyIds.map((e) => gt.String(e)) : [],
        };
    },
    toJSON(message) {
        var _a;
        const obj = {};
        if (message.chain !== "") {
            obj.chain = message.chain;
        }
        if ((_a = message.keyIds) === null || _a === void 0 ? void 0 : _a.length) {
            obj.keyIds = message.keyIds;
        }
        return obj;
    },
    create(base) {
        return exports.ExternalKeys.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b;
        const message = createBaseExternalKeys();
        message.chain = (_a = object.chain) !== null && _a !== void 0 ? _a : "";
        message.keyIds = ((_b = object.keyIds) === null || _b === void 0 ? void 0 : _b.map((e) => e)) || [];
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.ExternalKeys.$type, exports.ExternalKeys);
function createBaseValidatorStatus() {
    return {
        $type: "axelar.tss.v1beta1.ValidatorStatus",
        validator: Buffer.alloc(0),
        suspendedUntil: long_1.default.UZERO,
    };
}
exports.ValidatorStatus = {
    $type: "axelar.tss.v1beta1.ValidatorStatus",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.validator.length !== 0) {
            writer.uint32(10).bytes(message.validator);
        }
        if (!message.suspendedUntil.equals(long_1.default.UZERO)) {
            writer.uint32(16).uint64(message.suspendedUntil);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseValidatorStatus();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.validator = reader.bytes();
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.suspendedUntil = reader.uint64();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.ValidatorStatus.$type,
            validator: isSet(object.validator) ? Buffer.from(bytesFromBase64(object.validator)) : Buffer.alloc(0),
            suspendedUntil: isSet(object.suspendedUntil) ? long_1.default.fromValue(object.suspendedUntil) : long_1.default.UZERO,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.validator.length !== 0) {
            obj.validator = base64FromBytes(message.validator);
        }
        if (!message.suspendedUntil.equals(long_1.default.UZERO)) {
            obj.suspendedUntil = (message.suspendedUntil || long_1.default.UZERO).toString();
        }
        return obj;
    },
    create(base) {
        return exports.ValidatorStatus.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a;
        const message = createBaseValidatorStatus();
        message.validator = (_a = object.validator) !== null && _a !== void 0 ? _a : Buffer.alloc(0);
        message.suspendedUntil =
            object.suspendedUntil !== undefined && object.suspendedUntil !== null
                ? long_1.default.fromValue(object.suspendedUntil)
                : long_1.default.UZERO;
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.ValidatorStatus.$type, exports.ValidatorStatus);
const gt = (() => {
    if (typeof globalThis !== "undefined") {
        return globalThis;
    }
    if (typeof self !== "undefined") {
        return self;
    }
    if (typeof window !== "undefined") {
        return window;
    }
    if (typeof global !== "undefined") {
        return global;
    }
    throw "Unable to locate global object";
})();
function bytesFromBase64(b64) {
    return Uint8Array.from(gt.Buffer.from(b64, "base64"));
}
function base64FromBytes(arr) {
    return gt.Buffer.from(arr).toString("base64");
}
if (minimal_1.default.util.Long !== long_1.default) {
    minimal_1.default.util.Long = long_1.default;
    minimal_1.default.configure();
}
function isObject(value) {
    return typeof value === "object" && value !== null;
}
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=types.js.map