"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.33.4
// source: axelar/evm/v1beta1/genesis.proto
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.GenesisState_Chain = exports.GenesisState = exports.protobufPackage = void 0;
/* eslint-disable */
const long_1 = __importDefault(require("long"));
const minimal_1 = __importDefault(require("protobufjs/minimal"));
const typeRegistry_1 = require("../../../typeRegistry");
const queuer_1 = require("../../utils/v1beta1/queuer");
const params_1 = require("./params");
const types_1 = require("./types");
exports.protobufPackage = "axelar.evm.v1beta1";
function createBaseGenesisState() {
    return { $type: "axelar.evm.v1beta1.GenesisState", chains: [] };
}
exports.GenesisState = {
    $type: "axelar.evm.v1beta1.GenesisState",
    encode(message, writer = minimal_1.default.Writer.create()) {
        for (const v of message.chains) {
            exports.GenesisState_Chain.encode(v, writer.uint32(26).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseGenesisState();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.chains.push(exports.GenesisState_Chain.decode(reader, reader.uint32()));
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.GenesisState.$type,
            chains: gt.Array.isArray(object === null || object === void 0 ? void 0 : object.chains)
                ? object.chains.map((e) => exports.GenesisState_Chain.fromJSON(e))
                : [],
        };
    },
    toJSON(message) {
        var _a;
        const obj = {};
        if ((_a = message.chains) === null || _a === void 0 ? void 0 : _a.length) {
            obj.chains = message.chains.map((e) => exports.GenesisState_Chain.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return exports.GenesisState.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a;
        const message = createBaseGenesisState();
        message.chains = ((_a = object.chains) === null || _a === void 0 ? void 0 : _a.map((e) => exports.GenesisState_Chain.fromPartial(e))) || [];
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.GenesisState.$type, exports.GenesisState);
function createBaseGenesisState_Chain() {
    return {
        $type: "axelar.evm.v1beta1.GenesisState.Chain",
        params: undefined,
        burnerInfos: [],
        commandQueue: undefined,
        confirmedDeposits: [],
        burnedDeposits: [],
        commandBatches: [],
        gateway: undefined,
        tokens: [],
        events: [],
        confirmedEventQueue: undefined,
        legacyConfirmedDeposits: [],
        legacyBurnedDeposits: [],
    };
}
exports.GenesisState_Chain = {
    $type: "axelar.evm.v1beta1.GenesisState.Chain",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.params !== undefined) {
            params_1.Params.encode(message.params, writer.uint32(10).fork()).ldelim();
        }
        for (const v of message.burnerInfos) {
            types_1.BurnerInfo.encode(v, writer.uint32(18).fork()).ldelim();
        }
        if (message.commandQueue !== undefined) {
            queuer_1.QueueState.encode(message.commandQueue, writer.uint32(26).fork()).ldelim();
        }
        for (const v of message.confirmedDeposits) {
            types_1.ERC20Deposit.encode(v, writer.uint32(34).fork()).ldelim();
        }
        for (const v of message.burnedDeposits) {
            types_1.ERC20Deposit.encode(v, writer.uint32(42).fork()).ldelim();
        }
        for (const v of message.commandBatches) {
            types_1.CommandBatchMetadata.encode(v, writer.uint32(66).fork()).ldelim();
        }
        if (message.gateway !== undefined) {
            types_1.Gateway.encode(message.gateway, writer.uint32(74).fork()).ldelim();
        }
        for (const v of message.tokens) {
            types_1.ERC20TokenMetadata.encode(v, writer.uint32(82).fork()).ldelim();
        }
        for (const v of message.events) {
            types_1.Event.encode(v, writer.uint32(90).fork()).ldelim();
        }
        if (message.confirmedEventQueue !== undefined) {
            queuer_1.QueueState.encode(message.confirmedEventQueue, writer.uint32(98).fork()).ldelim();
        }
        for (const v of message.legacyConfirmedDeposits) {
            types_1.ERC20Deposit.encode(v, writer.uint32(106).fork()).ldelim();
        }
        for (const v of message.legacyBurnedDeposits) {
            types_1.ERC20Deposit.encode(v, writer.uint32(114).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseGenesisState_Chain();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.params = params_1.Params.decode(reader, reader.uint32());
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.burnerInfos.push(types_1.BurnerInfo.decode(reader, reader.uint32()));
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.commandQueue = queuer_1.QueueState.decode(reader, reader.uint32());
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.confirmedDeposits.push(types_1.ERC20Deposit.decode(reader, reader.uint32()));
                    continue;
                case 5:
                    if (tag !== 42) {
                        break;
                    }
                    message.burnedDeposits.push(types_1.ERC20Deposit.decode(reader, reader.uint32()));
                    continue;
                case 8:
                    if (tag !== 66) {
                        break;
                    }
                    message.commandBatches.push(types_1.CommandBatchMetadata.decode(reader, reader.uint32()));
                    continue;
                case 9:
                    if (tag !== 74) {
                        break;
                    }
                    message.gateway = types_1.Gateway.decode(reader, reader.uint32());
                    continue;
                case 10:
                    if (tag !== 82) {
                        break;
                    }
                    message.tokens.push(types_1.ERC20TokenMetadata.decode(reader, reader.uint32()));
                    continue;
                case 11:
                    if (tag !== 90) {
                        break;
                    }
                    message.events.push(types_1.Event.decode(reader, reader.uint32()));
                    continue;
                case 12:
                    if (tag !== 98) {
                        break;
                    }
                    message.confirmedEventQueue = queuer_1.QueueState.decode(reader, reader.uint32());
                    continue;
                case 13:
                    if (tag !== 106) {
                        break;
                    }
                    message.legacyConfirmedDeposits.push(types_1.ERC20Deposit.decode(reader, reader.uint32()));
                    continue;
                case 14:
                    if (tag !== 114) {
                        break;
                    }
                    message.legacyBurnedDeposits.push(types_1.ERC20Deposit.decode(reader, reader.uint32()));
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.GenesisState_Chain.$type,
            params: isSet(object.params) ? params_1.Params.fromJSON(object.params) : undefined,
            burnerInfos: gt.Array.isArray(object === null || object === void 0 ? void 0 : object.burnerInfos)
                ? object.burnerInfos.map((e) => types_1.BurnerInfo.fromJSON(e))
                : [],
            commandQueue: isSet(object.commandQueue) ? queuer_1.QueueState.fromJSON(object.commandQueue) : undefined,
            confirmedDeposits: gt.Array.isArray(object === null || object === void 0 ? void 0 : object.confirmedDeposits)
                ? object.confirmedDeposits.map((e) => types_1.ERC20Deposit.fromJSON(e))
                : [],
            burnedDeposits: gt.Array.isArray(object === null || object === void 0 ? void 0 : object.burnedDeposits)
                ? object.burnedDeposits.map((e) => types_1.ERC20Deposit.fromJSON(e))
                : [],
            commandBatches: gt.Array.isArray(object === null || object === void 0 ? void 0 : object.commandBatches)
                ? object.commandBatches.map((e) => types_1.CommandBatchMetadata.fromJSON(e))
                : [],
            gateway: isSet(object.gateway) ? types_1.Gateway.fromJSON(object.gateway) : undefined,
            tokens: gt.Array.isArray(object === null || object === void 0 ? void 0 : object.tokens)
                ? object.tokens.map((e) => types_1.ERC20TokenMetadata.fromJSON(e))
                : [],
            events: gt.Array.isArray(object === null || object === void 0 ? void 0 : object.events) ? object.events.map((e) => types_1.Event.fromJSON(e)) : [],
            confirmedEventQueue: isSet(object.confirmedEventQueue)
                ? queuer_1.QueueState.fromJSON(object.confirmedEventQueue)
                : undefined,
            legacyConfirmedDeposits: gt.Array.isArray(object === null || object === void 0 ? void 0 : object.legacyConfirmedDeposits)
                ? object.legacyConfirmedDeposits.map((e) => types_1.ERC20Deposit.fromJSON(e))
                : [],
            legacyBurnedDeposits: gt.Array.isArray(object === null || object === void 0 ? void 0 : object.legacyBurnedDeposits)
                ? object.legacyBurnedDeposits.map((e) => types_1.ERC20Deposit.fromJSON(e))
                : [],
        };
    },
    toJSON(message) {
        var _a, _b, _c, _d, _e, _f, _g, _h;
        const obj = {};
        if (message.params !== undefined) {
            obj.params = params_1.Params.toJSON(message.params);
        }
        if ((_a = message.burnerInfos) === null || _a === void 0 ? void 0 : _a.length) {
            obj.burnerInfos = message.burnerInfos.map((e) => types_1.BurnerInfo.toJSON(e));
        }
        if (message.commandQueue !== undefined) {
            obj.commandQueue = queuer_1.QueueState.toJSON(message.commandQueue);
        }
        if ((_b = message.confirmedDeposits) === null || _b === void 0 ? void 0 : _b.length) {
            obj.confirmedDeposits = message.confirmedDeposits.map((e) => types_1.ERC20Deposit.toJSON(e));
        }
        if ((_c = message.burnedDeposits) === null || _c === void 0 ? void 0 : _c.length) {
            obj.burnedDeposits = message.burnedDeposits.map((e) => types_1.ERC20Deposit.toJSON(e));
        }
        if ((_d = message.commandBatches) === null || _d === void 0 ? void 0 : _d.length) {
            obj.commandBatches = message.commandBatches.map((e) => types_1.CommandBatchMetadata.toJSON(e));
        }
        if (message.gateway !== undefined) {
            obj.gateway = types_1.Gateway.toJSON(message.gateway);
        }
        if ((_e = message.tokens) === null || _e === void 0 ? void 0 : _e.length) {
            obj.tokens = message.tokens.map((e) => types_1.ERC20TokenMetadata.toJSON(e));
        }
        if ((_f = message.events) === null || _f === void 0 ? void 0 : _f.length) {
            obj.events = message.events.map((e) => types_1.Event.toJSON(e));
        }
        if (message.confirmedEventQueue !== undefined) {
            obj.confirmedEventQueue = queuer_1.QueueState.toJSON(message.confirmedEventQueue);
        }
        if ((_g = message.legacyConfirmedDeposits) === null || _g === void 0 ? void 0 : _g.length) {
            obj.legacyConfirmedDeposits = message.legacyConfirmedDeposits.map((e) => types_1.ERC20Deposit.toJSON(e));
        }
        if ((_h = message.legacyBurnedDeposits) === null || _h === void 0 ? void 0 : _h.length) {
            obj.legacyBurnedDeposits = message.legacyBurnedDeposits.map((e) => types_1.ERC20Deposit.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return exports.GenesisState_Chain.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b, _c, _d, _e, _f, _g, _h;
        const message = createBaseGenesisState_Chain();
        message.params =
            object.params !== undefined && object.params !== null ? params_1.Params.fromPartial(object.params) : undefined;
        message.burnerInfos = ((_a = object.burnerInfos) === null || _a === void 0 ? void 0 : _a.map((e) => types_1.BurnerInfo.fromPartial(e))) || [];
        message.commandQueue =
            object.commandQueue !== undefined && object.commandQueue !== null
                ? queuer_1.QueueState.fromPartial(object.commandQueue)
                : undefined;
        message.confirmedDeposits = ((_b = object.confirmedDeposits) === null || _b === void 0 ? void 0 : _b.map((e) => types_1.ERC20Deposit.fromPartial(e))) || [];
        message.burnedDeposits = ((_c = object.burnedDeposits) === null || _c === void 0 ? void 0 : _c.map((e) => types_1.ERC20Deposit.fromPartial(e))) || [];
        message.commandBatches = ((_d = object.commandBatches) === null || _d === void 0 ? void 0 : _d.map((e) => types_1.CommandBatchMetadata.fromPartial(e))) || [];
        message.gateway =
            object.gateway !== undefined && object.gateway !== null
                ? types_1.Gateway.fromPartial(object.gateway)
                : undefined;
        message.tokens = ((_e = object.tokens) === null || _e === void 0 ? void 0 : _e.map((e) => types_1.ERC20TokenMetadata.fromPartial(e))) || [];
        message.events = ((_f = object.events) === null || _f === void 0 ? void 0 : _f.map((e) => types_1.Event.fromPartial(e))) || [];
        message.confirmedEventQueue =
            object.confirmedEventQueue !== undefined && object.confirmedEventQueue !== null
                ? queuer_1.QueueState.fromPartial(object.confirmedEventQueue)
                : undefined;
        message.legacyConfirmedDeposits =
            ((_g = object.legacyConfirmedDeposits) === null || _g === void 0 ? void 0 : _g.map((e) => types_1.ERC20Deposit.fromPartial(e))) || [];
        message.legacyBurnedDeposits = ((_h = object.legacyBurnedDeposits) === null || _h === void 0 ? void 0 : _h.map((e) => types_1.ERC20Deposit.fromPartial(e))) || [];
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.GenesisState_Chain.$type, exports.GenesisState_Chain);
const gt = (() => {
    if (typeof globalThis !== "undefined") {
        return globalThis;
    }
    if (typeof self !== "undefined") {
        return self;
    }
    if (typeof window !== "undefined") {
        return window;
    }
    if (typeof global !== "undefined") {
        return global;
    }
    throw "Unable to locate global object";
})();
if (minimal_1.default.util.Long !== long_1.default) {
    minimal_1.default.util.Long = long_1.default;
    minimal_1.default.configure();
}
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=genesis.js.map