"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.31.1
// source: axelar/nexus/v1beta1/params.proto
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Params = exports.protobufPackage = void 0;
/* eslint-disable */
const long_1 = __importDefault(require("long"));
const minimal_1 = __importDefault(require("protobufjs/minimal"));
const typeRegistry_1 = require("../../../typeRegistry");
const threshold_1 = require("../../utils/v1beta1/threshold");
exports.protobufPackage = "axelar.nexus.v1beta1";
function createBaseParams() {
    return {
        $type: "axelar.nexus.v1beta1.Params",
        chainActivationThreshold: undefined,
        chainMaintainerMissingVoteThreshold: undefined,
        chainMaintainerIncorrectVoteThreshold: undefined,
        chainMaintainerCheckWindow: 0,
        gateway: Buffer.alloc(0),
        endBlockerLimit: long_1.default.UZERO,
    };
}
exports.Params = {
    $type: "axelar.nexus.v1beta1.Params",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.chainActivationThreshold !== undefined) {
            threshold_1.Threshold.encode(message.chainActivationThreshold, writer.uint32(10).fork()).ldelim();
        }
        if (message.chainMaintainerMissingVoteThreshold !== undefined) {
            threshold_1.Threshold.encode(message.chainMaintainerMissingVoteThreshold, writer.uint32(18).fork()).ldelim();
        }
        if (message.chainMaintainerIncorrectVoteThreshold !== undefined) {
            threshold_1.Threshold.encode(message.chainMaintainerIncorrectVoteThreshold, writer.uint32(26).fork()).ldelim();
        }
        if (message.chainMaintainerCheckWindow !== 0) {
            writer.uint32(32).int32(message.chainMaintainerCheckWindow);
        }
        if (message.gateway.length !== 0) {
            writer.uint32(42).bytes(message.gateway);
        }
        if (!message.endBlockerLimit.equals(long_1.default.UZERO)) {
            writer.uint32(48).uint64(message.endBlockerLimit);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseParams();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.chainActivationThreshold = threshold_1.Threshold.decode(reader, reader.uint32());
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.chainMaintainerMissingVoteThreshold = threshold_1.Threshold.decode(reader, reader.uint32());
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.chainMaintainerIncorrectVoteThreshold = threshold_1.Threshold.decode(reader, reader.uint32());
                    continue;
                case 4:
                    if (tag !== 32) {
                        break;
                    }
                    message.chainMaintainerCheckWindow = reader.int32();
                    continue;
                case 5:
                    if (tag !== 42) {
                        break;
                    }
                    message.gateway = reader.bytes();
                    continue;
                case 6:
                    if (tag !== 48) {
                        break;
                    }
                    message.endBlockerLimit = reader.uint64();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.Params.$type,
            chainActivationThreshold: isSet(object.chainActivationThreshold)
                ? threshold_1.Threshold.fromJSON(object.chainActivationThreshold)
                : undefined,
            chainMaintainerMissingVoteThreshold: isSet(object.chainMaintainerMissingVoteThreshold)
                ? threshold_1.Threshold.fromJSON(object.chainMaintainerMissingVoteThreshold)
                : undefined,
            chainMaintainerIncorrectVoteThreshold: isSet(object.chainMaintainerIncorrectVoteThreshold)
                ? threshold_1.Threshold.fromJSON(object.chainMaintainerIncorrectVoteThreshold)
                : undefined,
            chainMaintainerCheckWindow: isSet(object.chainMaintainerCheckWindow)
                ? gt.Number(object.chainMaintainerCheckWindow)
                : 0,
            gateway: isSet(object.gateway) ? Buffer.from(bytesFromBase64(object.gateway)) : Buffer.alloc(0),
            endBlockerLimit: isSet(object.endBlockerLimit) ? long_1.default.fromValue(object.endBlockerLimit) : long_1.default.UZERO,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.chainActivationThreshold !== undefined) {
            obj.chainActivationThreshold = threshold_1.Threshold.toJSON(message.chainActivationThreshold);
        }
        if (message.chainMaintainerMissingVoteThreshold !== undefined) {
            obj.chainMaintainerMissingVoteThreshold = threshold_1.Threshold.toJSON(message.chainMaintainerMissingVoteThreshold);
        }
        if (message.chainMaintainerIncorrectVoteThreshold !== undefined) {
            obj.chainMaintainerIncorrectVoteThreshold = threshold_1.Threshold.toJSON(message.chainMaintainerIncorrectVoteThreshold);
        }
        if (message.chainMaintainerCheckWindow !== 0) {
            obj.chainMaintainerCheckWindow = Math.round(message.chainMaintainerCheckWindow);
        }
        if (message.gateway.length !== 0) {
            obj.gateway = base64FromBytes(message.gateway);
        }
        if (!message.endBlockerLimit.equals(long_1.default.UZERO)) {
            obj.endBlockerLimit = (message.endBlockerLimit || long_1.default.UZERO).toString();
        }
        return obj;
    },
    create(base) {
        return exports.Params.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b;
        const message = createBaseParams();
        message.chainActivationThreshold =
            object.chainActivationThreshold !== undefined && object.chainActivationThreshold !== null
                ? threshold_1.Threshold.fromPartial(object.chainActivationThreshold)
                : undefined;
        message.chainMaintainerMissingVoteThreshold =
            object.chainMaintainerMissingVoteThreshold !== undefined &&
                object.chainMaintainerMissingVoteThreshold !== null
                ? threshold_1.Threshold.fromPartial(object.chainMaintainerMissingVoteThreshold)
                : undefined;
        message.chainMaintainerIncorrectVoteThreshold =
            object.chainMaintainerIncorrectVoteThreshold !== undefined &&
                object.chainMaintainerIncorrectVoteThreshold !== null
                ? threshold_1.Threshold.fromPartial(object.chainMaintainerIncorrectVoteThreshold)
                : undefined;
        message.chainMaintainerCheckWindow = (_a = object.chainMaintainerCheckWindow) !== null && _a !== void 0 ? _a : 0;
        message.gateway = (_b = object.gateway) !== null && _b !== void 0 ? _b : Buffer.alloc(0);
        message.endBlockerLimit =
            object.endBlockerLimit !== undefined && object.endBlockerLimit !== null
                ? long_1.default.fromValue(object.endBlockerLimit)
                : long_1.default.UZERO;
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.Params.$type, exports.Params);
const gt = (() => {
    if (typeof globalThis !== "undefined") {
        return globalThis;
    }
    if (typeof self !== "undefined") {
        return self;
    }
    if (typeof window !== "undefined") {
        return window;
    }
    if (typeof global !== "undefined") {
        return global;
    }
    throw "Unable to locate global object";
})();
function bytesFromBase64(b64) {
    return Uint8Array.from(gt.Buffer.from(b64, "base64"));
}
function base64FromBytes(arr) {
    return gt.Buffer.from(arr).toString("base64");
}
if (minimal_1.default.util.Long !== long_1.default) {
    minimal_1.default.util.Long = long_1.default;
    minimal_1.default.configure();
}
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=params.js.map