"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.21.12
// source: axelar/nexus/v1beta1/tx.proto
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpdateParamsResponse = exports.UpdateParamsRequest = exports.SetTransferRateLimitResponse = exports.SetTransferRateLimitRequest = exports.RegisterAssetFeeResponse = exports.RegisterAssetFeeRequest = exports.DeactivateChainResponse = exports.DeactivateChainRequest = exports.ActivateChainResponse = exports.ActivateChainRequest = exports.DeregisterChainMaintainerResponse = exports.DeregisterChainMaintainerRequest = exports.RegisterChainMaintainerResponse = exports.RegisterChainMaintainerRequest = exports.protobufPackage = void 0;
/* eslint-disable */
const long_1 = __importDefault(require("long"));
const minimal_1 = __importDefault(require("protobufjs/minimal"));
const coin_1 = require("../../../cosmos/base/v1beta1/coin");
const duration_1 = require("../../../google/protobuf/duration");
const typeRegistry_1 = require("../../../typeRegistry");
const types_1 = require("../exported/v1beta1/types");
const params_1 = require("./params");
exports.protobufPackage = "axelar.nexus.v1beta1";
function createBaseRegisterChainMaintainerRequest() {
    return { $type: "axelar.nexus.v1beta1.RegisterChainMaintainerRequest", chains: [], sender: "" };
}
exports.RegisterChainMaintainerRequest = {
    $type: "axelar.nexus.v1beta1.RegisterChainMaintainerRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        for (const v of message.chains) {
            writer.uint32(18).string(v);
        }
        if (message.sender !== "") {
            writer.uint32(26).string(message.sender);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRegisterChainMaintainerRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.chains.push(reader.string());
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.sender = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.RegisterChainMaintainerRequest.$type,
            chains: gt.Array.isArray(object === null || object === void 0 ? void 0 : object.chains) ? object.chains.map((e) => gt.String(e)) : [],
            sender: isSet(object.sender) ? gt.String(object.sender) : "",
        };
    },
    toJSON(message) {
        var _a;
        const obj = {};
        if ((_a = message.chains) === null || _a === void 0 ? void 0 : _a.length) {
            obj.chains = message.chains;
        }
        if (message.sender !== "") {
            obj.sender = message.sender;
        }
        return obj;
    },
    create(base) {
        return exports.RegisterChainMaintainerRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b;
        const message = createBaseRegisterChainMaintainerRequest();
        message.chains = ((_a = object.chains) === null || _a === void 0 ? void 0 : _a.map((e) => e)) || [];
        message.sender = (_b = object.sender) !== null && _b !== void 0 ? _b : "";
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.RegisterChainMaintainerRequest.$type, exports.RegisterChainMaintainerRequest);
function createBaseRegisterChainMaintainerResponse() {
    return { $type: "axelar.nexus.v1beta1.RegisterChainMaintainerResponse" };
}
exports.RegisterChainMaintainerResponse = {
    $type: "axelar.nexus.v1beta1.RegisterChainMaintainerResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRegisterChainMaintainerResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.RegisterChainMaintainerResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.RegisterChainMaintainerResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseRegisterChainMaintainerResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.RegisterChainMaintainerResponse.$type, exports.RegisterChainMaintainerResponse);
function createBaseDeregisterChainMaintainerRequest() {
    return { $type: "axelar.nexus.v1beta1.DeregisterChainMaintainerRequest", chains: [], sender: "" };
}
exports.DeregisterChainMaintainerRequest = {
    $type: "axelar.nexus.v1beta1.DeregisterChainMaintainerRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        for (const v of message.chains) {
            writer.uint32(18).string(v);
        }
        if (message.sender !== "") {
            writer.uint32(26).string(message.sender);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseDeregisterChainMaintainerRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.chains.push(reader.string());
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.sender = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.DeregisterChainMaintainerRequest.$type,
            chains: gt.Array.isArray(object === null || object === void 0 ? void 0 : object.chains) ? object.chains.map((e) => gt.String(e)) : [],
            sender: isSet(object.sender) ? gt.String(object.sender) : "",
        };
    },
    toJSON(message) {
        var _a;
        const obj = {};
        if ((_a = message.chains) === null || _a === void 0 ? void 0 : _a.length) {
            obj.chains = message.chains;
        }
        if (message.sender !== "") {
            obj.sender = message.sender;
        }
        return obj;
    },
    create(base) {
        return exports.DeregisterChainMaintainerRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b;
        const message = createBaseDeregisterChainMaintainerRequest();
        message.chains = ((_a = object.chains) === null || _a === void 0 ? void 0 : _a.map((e) => e)) || [];
        message.sender = (_b = object.sender) !== null && _b !== void 0 ? _b : "";
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.DeregisterChainMaintainerRequest.$type, exports.DeregisterChainMaintainerRequest);
function createBaseDeregisterChainMaintainerResponse() {
    return { $type: "axelar.nexus.v1beta1.DeregisterChainMaintainerResponse" };
}
exports.DeregisterChainMaintainerResponse = {
    $type: "axelar.nexus.v1beta1.DeregisterChainMaintainerResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseDeregisterChainMaintainerResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.DeregisterChainMaintainerResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.DeregisterChainMaintainerResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseDeregisterChainMaintainerResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.DeregisterChainMaintainerResponse.$type, exports.DeregisterChainMaintainerResponse);
function createBaseActivateChainRequest() {
    return { $type: "axelar.nexus.v1beta1.ActivateChainRequest", chains: [], sender: "" };
}
exports.ActivateChainRequest = {
    $type: "axelar.nexus.v1beta1.ActivateChainRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        for (const v of message.chains) {
            writer.uint32(18).string(v);
        }
        if (message.sender !== "") {
            writer.uint32(26).string(message.sender);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseActivateChainRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.chains.push(reader.string());
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.sender = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.ActivateChainRequest.$type,
            chains: gt.Array.isArray(object === null || object === void 0 ? void 0 : object.chains) ? object.chains.map((e) => gt.String(e)) : [],
            sender: isSet(object.sender) ? gt.String(object.sender) : "",
        };
    },
    toJSON(message) {
        var _a;
        const obj = {};
        if ((_a = message.chains) === null || _a === void 0 ? void 0 : _a.length) {
            obj.chains = message.chains;
        }
        if (message.sender !== "") {
            obj.sender = message.sender;
        }
        return obj;
    },
    create(base) {
        return exports.ActivateChainRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b;
        const message = createBaseActivateChainRequest();
        message.chains = ((_a = object.chains) === null || _a === void 0 ? void 0 : _a.map((e) => e)) || [];
        message.sender = (_b = object.sender) !== null && _b !== void 0 ? _b : "";
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.ActivateChainRequest.$type, exports.ActivateChainRequest);
function createBaseActivateChainResponse() {
    return { $type: "axelar.nexus.v1beta1.ActivateChainResponse" };
}
exports.ActivateChainResponse = {
    $type: "axelar.nexus.v1beta1.ActivateChainResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseActivateChainResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.ActivateChainResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.ActivateChainResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseActivateChainResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.ActivateChainResponse.$type, exports.ActivateChainResponse);
function createBaseDeactivateChainRequest() {
    return { $type: "axelar.nexus.v1beta1.DeactivateChainRequest", chains: [], sender: "" };
}
exports.DeactivateChainRequest = {
    $type: "axelar.nexus.v1beta1.DeactivateChainRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        for (const v of message.chains) {
            writer.uint32(18).string(v);
        }
        if (message.sender !== "") {
            writer.uint32(26).string(message.sender);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseDeactivateChainRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.chains.push(reader.string());
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.sender = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.DeactivateChainRequest.$type,
            chains: gt.Array.isArray(object === null || object === void 0 ? void 0 : object.chains) ? object.chains.map((e) => gt.String(e)) : [],
            sender: isSet(object.sender) ? gt.String(object.sender) : "",
        };
    },
    toJSON(message) {
        var _a;
        const obj = {};
        if ((_a = message.chains) === null || _a === void 0 ? void 0 : _a.length) {
            obj.chains = message.chains;
        }
        if (message.sender !== "") {
            obj.sender = message.sender;
        }
        return obj;
    },
    create(base) {
        return exports.DeactivateChainRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b;
        const message = createBaseDeactivateChainRequest();
        message.chains = ((_a = object.chains) === null || _a === void 0 ? void 0 : _a.map((e) => e)) || [];
        message.sender = (_b = object.sender) !== null && _b !== void 0 ? _b : "";
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.DeactivateChainRequest.$type, exports.DeactivateChainRequest);
function createBaseDeactivateChainResponse() {
    return { $type: "axelar.nexus.v1beta1.DeactivateChainResponse" };
}
exports.DeactivateChainResponse = {
    $type: "axelar.nexus.v1beta1.DeactivateChainResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseDeactivateChainResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.DeactivateChainResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.DeactivateChainResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseDeactivateChainResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.DeactivateChainResponse.$type, exports.DeactivateChainResponse);
function createBaseRegisterAssetFeeRequest() {
    return { $type: "axelar.nexus.v1beta1.RegisterAssetFeeRequest", feeInfo: undefined, sender: "" };
}
exports.RegisterAssetFeeRequest = {
    $type: "axelar.nexus.v1beta1.RegisterAssetFeeRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.feeInfo !== undefined) {
            types_1.FeeInfo.encode(message.feeInfo, writer.uint32(18).fork()).ldelim();
        }
        if (message.sender !== "") {
            writer.uint32(26).string(message.sender);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRegisterAssetFeeRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.feeInfo = types_1.FeeInfo.decode(reader, reader.uint32());
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.sender = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.RegisterAssetFeeRequest.$type,
            feeInfo: isSet(object.feeInfo) ? types_1.FeeInfo.fromJSON(object.feeInfo) : undefined,
            sender: isSet(object.sender) ? gt.String(object.sender) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.feeInfo !== undefined) {
            obj.feeInfo = types_1.FeeInfo.toJSON(message.feeInfo);
        }
        if (message.sender !== "") {
            obj.sender = message.sender;
        }
        return obj;
    },
    create(base) {
        return exports.RegisterAssetFeeRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a;
        const message = createBaseRegisterAssetFeeRequest();
        message.feeInfo =
            object.feeInfo !== undefined && object.feeInfo !== null
                ? types_1.FeeInfo.fromPartial(object.feeInfo)
                : undefined;
        message.sender = (_a = object.sender) !== null && _a !== void 0 ? _a : "";
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.RegisterAssetFeeRequest.$type, exports.RegisterAssetFeeRequest);
function createBaseRegisterAssetFeeResponse() {
    return { $type: "axelar.nexus.v1beta1.RegisterAssetFeeResponse" };
}
exports.RegisterAssetFeeResponse = {
    $type: "axelar.nexus.v1beta1.RegisterAssetFeeResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRegisterAssetFeeResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.RegisterAssetFeeResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.RegisterAssetFeeResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseRegisterAssetFeeResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.RegisterAssetFeeResponse.$type, exports.RegisterAssetFeeResponse);
function createBaseSetTransferRateLimitRequest() {
    return {
        $type: "axelar.nexus.v1beta1.SetTransferRateLimitRequest",
        chain: "",
        limit: undefined,
        window: undefined,
        sender: "",
    };
}
exports.SetTransferRateLimitRequest = {
    $type: "axelar.nexus.v1beta1.SetTransferRateLimitRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.chain !== "") {
            writer.uint32(18).string(message.chain);
        }
        if (message.limit !== undefined) {
            coin_1.Coin.encode(message.limit, writer.uint32(26).fork()).ldelim();
        }
        if (message.window !== undefined) {
            duration_1.Duration.encode(message.window, writer.uint32(34).fork()).ldelim();
        }
        if (message.sender !== "") {
            writer.uint32(42).string(message.sender);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSetTransferRateLimitRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.chain = reader.string();
                    continue;
                case 3:
                    if (tag !== 26) {
                        break;
                    }
                    message.limit = coin_1.Coin.decode(reader, reader.uint32());
                    continue;
                case 4:
                    if (tag !== 34) {
                        break;
                    }
                    message.window = duration_1.Duration.decode(reader, reader.uint32());
                    continue;
                case 5:
                    if (tag !== 42) {
                        break;
                    }
                    message.sender = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.SetTransferRateLimitRequest.$type,
            chain: isSet(object.chain) ? gt.String(object.chain) : "",
            limit: isSet(object.limit) ? coin_1.Coin.fromJSON(object.limit) : undefined,
            window: isSet(object.window) ? duration_1.Duration.fromJSON(object.window) : undefined,
            sender: isSet(object.sender) ? gt.String(object.sender) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.chain !== "") {
            obj.chain = message.chain;
        }
        if (message.limit !== undefined) {
            obj.limit = coin_1.Coin.toJSON(message.limit);
        }
        if (message.window !== undefined) {
            obj.window = duration_1.Duration.toJSON(message.window);
        }
        if (message.sender !== "") {
            obj.sender = message.sender;
        }
        return obj;
    },
    create(base) {
        return exports.SetTransferRateLimitRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a, _b;
        const message = createBaseSetTransferRateLimitRequest();
        message.chain = (_a = object.chain) !== null && _a !== void 0 ? _a : "";
        message.limit =
            object.limit !== undefined && object.limit !== null ? coin_1.Coin.fromPartial(object.limit) : undefined;
        message.window =
            object.window !== undefined && object.window !== null ? duration_1.Duration.fromPartial(object.window) : undefined;
        message.sender = (_b = object.sender) !== null && _b !== void 0 ? _b : "";
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.SetTransferRateLimitRequest.$type, exports.SetTransferRateLimitRequest);
function createBaseSetTransferRateLimitResponse() {
    return { $type: "axelar.nexus.v1beta1.SetTransferRateLimitResponse" };
}
exports.SetTransferRateLimitResponse = {
    $type: "axelar.nexus.v1beta1.SetTransferRateLimitResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSetTransferRateLimitResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.SetTransferRateLimitResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.SetTransferRateLimitResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseSetTransferRateLimitResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.SetTransferRateLimitResponse.$type, exports.SetTransferRateLimitResponse);
function createBaseUpdateParamsRequest() {
    return { $type: "axelar.nexus.v1beta1.UpdateParamsRequest", authority: "", params: undefined };
}
exports.UpdateParamsRequest = {
    $type: "axelar.nexus.v1beta1.UpdateParamsRequest",
    encode(message, writer = minimal_1.default.Writer.create()) {
        if (message.authority !== "") {
            writer.uint32(10).string(message.authority);
        }
        if (message.params !== undefined) {
            params_1.Params.encode(message.params, writer.uint32(18).fork()).ldelim();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseUpdateParamsRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.authority = reader.string();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.params = params_1.Params.decode(reader, reader.uint32());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            $type: exports.UpdateParamsRequest.$type,
            authority: isSet(object.authority) ? gt.String(object.authority) : "",
            params: isSet(object.params) ? params_1.Params.fromJSON(object.params) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.authority !== "") {
            obj.authority = message.authority;
        }
        if (message.params !== undefined) {
            obj.params = params_1.Params.toJSON(message.params);
        }
        return obj;
    },
    create(base) {
        return exports.UpdateParamsRequest.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(object) {
        var _a;
        const message = createBaseUpdateParamsRequest();
        message.authority = (_a = object.authority) !== null && _a !== void 0 ? _a : "";
        message.params =
            object.params !== undefined && object.params !== null ? params_1.Params.fromPartial(object.params) : undefined;
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.UpdateParamsRequest.$type, exports.UpdateParamsRequest);
function createBaseUpdateParamsResponse() {
    return { $type: "axelar.nexus.v1beta1.UpdateParamsResponse" };
}
exports.UpdateParamsResponse = {
    $type: "axelar.nexus.v1beta1.UpdateParamsResponse",
    encode(_, writer = minimal_1.default.Writer.create()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof minimal_1.default.Reader ? input : minimal_1.default.Reader.create(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseUpdateParamsResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skipType(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return { $type: exports.UpdateParamsResponse.$type };
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.UpdateParamsResponse.fromPartial(base !== null && base !== void 0 ? base : {});
    },
    fromPartial(_) {
        const message = createBaseUpdateParamsResponse();
        return message;
    },
};
typeRegistry_1.messageTypeRegistry.set(exports.UpdateParamsResponse.$type, exports.UpdateParamsResponse);
const gt = (() => {
    if (typeof globalThis !== "undefined") {
        return globalThis;
    }
    if (typeof self !== "undefined") {
        return self;
    }
    if (typeof window !== "undefined") {
        return window;
    }
    if (typeof global !== "undefined") {
        return global;
    }
    throw "Unable to locate global object";
})();
if (minimal_1.default.util.Long !== long_1.default) {
    minimal_1.default.util.Long = long_1.default;
    minimal_1.default.configure();
}
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=tx.js.map